/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TRANSPORTE.VISTAS.UNIDADES;

/**
 *
 * @author milag
 */
public class formTipoLocalizador extends javax.swing.JPanel {

    /**
     * Creates new form formTipoLocalizador
     */
    public formTipoLocalizador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUser3 = new javax.swing.JPanel();
        lblTitlePersona2 = new javax.swing.JLabel();
        lblEstatusPersona2 = new javax.swing.JLabel();
        lblCodigoTipoLocalizador = new javax.swing.JLabel();
        txtCodigoTipoLocalizador = new javax.swing.JTextField();
        lblInfoTipoLocalizador = new javax.swing.JLabel();
        lblDescripccionTipoLocalizador = new javax.swing.JLabel();
        txtDescripccionTipoLocalizador = new javax.swing.JTextField();
        btnCancelFormCarga = new javax.swing.JButton();
        btnCleanFormCarga = new javax.swing.JButton();
        btnSetFormCarga = new javax.swing.JButton();
        btnBuscarTipoLocalizador = new javax.swing.JButton();
        btnEliminarFormCarga = new javax.swing.JButton();

        pnlUser3.setBackground(new java.awt.Color(255, 255, 255));

        lblTitlePersona2.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitlePersona2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePersona2.setText("TIPO DE LOCALIZADOR");

        lblEstatusPersona2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblEstatusPersona2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstatusPersona2.setText("0");
        lblEstatusPersona2.setEnabled(false);

        lblCodigoTipoLocalizador.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCodigoTipoLocalizador.setText("CODIGO");

        txtCodigoTipoLocalizador.setBackground(new java.awt.Color(250, 250, 250));
        txtCodigoTipoLocalizador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtCodigoTipoLocalizador.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCodigoTipoLocalizador.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigoTipoLocalizador.setOpaque(true);

        lblInfoTipoLocalizador.setForeground(new java.awt.Color(255, 0, 51));
        lblInfoTipoLocalizador.setText("* ");

        lblDescripccionTipoLocalizador.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblDescripccionTipoLocalizador.setText("DESCRIPCCION");

        txtDescripccionTipoLocalizador.setBackground(new java.awt.Color(250, 250, 250));
        txtDescripccionTipoLocalizador.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtDescripccionTipoLocalizador.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescripccionTipoLocalizador.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDescripccionTipoLocalizador.setOpaque(true);

        btnCancelFormCarga.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelFormCarga.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelFormCarga.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelFormCarga.setText("CANCELAR");
        btnCancelFormCarga.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelFormCarga.setIconTextGap(10);
        btnCancelFormCarga.setMargin(new java.awt.Insets(2, 1, 3, 14));

        btnCleanFormCarga.setBackground(new java.awt.Color(230, 230, 230));
        btnCleanFormCarga.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCleanFormCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMop.png"))); // NOI18N
        btnCleanFormCarga.setText("LIMPIAR");
        btnCleanFormCarga.setToolTipText("");
        btnCleanFormCarga.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCleanFormCarga.setIconTextGap(10);
        btnCleanFormCarga.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCleanFormCarga.setMaximumSize(new java.awt.Dimension(125, 35));
        btnCleanFormCarga.setMinimumSize(new java.awt.Dimension(125, 35));
        btnCleanFormCarga.setPreferredSize(new java.awt.Dimension(125, 35));

        btnSetFormCarga.setBackground(new java.awt.Color(153, 255, 153));
        btnSetFormCarga.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSetFormCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnSetFormCarga.setText("REGISTRAR");
        btnSetFormCarga.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSetFormCarga.setIconTextGap(10);
        btnSetFormCarga.setMargin(new java.awt.Insets(0, 0, 0, 0));

        btnBuscarTipoLocalizador.setBackground(new java.awt.Color(231, 255, 255));
        btnBuscarTipoLocalizador.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnBuscarTipoLocalizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnBuscarTipoLocalizador.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBuscarTipoLocalizador.setIconTextGap(10);
        btnBuscarTipoLocalizador.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBuscarTipoLocalizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarTipoLocalizadorActionPerformed(evt);
            }
        });

        btnEliminarFormCarga.setBackground(new java.awt.Color(102, 0, 0));
        btnEliminarFormCarga.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEliminarFormCarga.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarFormCarga.setText("ELIMINAR");
        btnEliminarFormCarga.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminarFormCarga.setIconTextGap(10);
        btnEliminarFormCarga.setMargin(new java.awt.Insets(2, 1, 3, 14));

        javax.swing.GroupLayout pnlUser3Layout = new javax.swing.GroupLayout(pnlUser3);
        pnlUser3.setLayout(pnlUser3Layout);
        pnlUser3Layout.setHorizontalGroup(
            pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUser3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripccionTipoLocalizador)
                    .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlUser3Layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(btnEliminarFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSetFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUser3Layout.createSequentialGroup()
                            .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnlUser3Layout.createSequentialGroup()
                                    .addComponent(lblCodigoTipoLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnBuscarTipoLocalizador))
                                .addComponent(btnCancelFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnlUser3Layout.createSequentialGroup()
                                    .addGap(58, 58, 58)
                                    .addComponent(btnCleanFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlUser3Layout.createSequentialGroup()
                                    .addGap(20, 20, 20)
                                    .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtDescripccionTipoLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtCodigoTipoLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlUser3Layout.createSequentialGroup()
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addComponent(lblEstatusPersona2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblInfoTipoLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitlePersona2, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlUser3Layout.setVerticalGroup(
            pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser3Layout.createSequentialGroup()
                .addComponent(lblTitlePersona2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoTipoLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstatusPersona2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigoTipoLocalizador)
                        .addComponent(txtCodigoTipoLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarTipoLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripccionTipoLocalizador)
                    .addComponent(txtDescripccionTipoLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCleanFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarTipoLocalizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarTipoLocalizadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarTipoLocalizadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarTipoLocalizador;
    public javax.swing.JButton btnCancelFormCarga;
    public javax.swing.JButton btnCleanFormCarga;
    public javax.swing.JButton btnEliminarFormCarga;
    public javax.swing.JButton btnSetFormCarga;
    public javax.swing.JLabel lblCodigoTipoLocalizador;
    public javax.swing.JLabel lblDescripccionTipoLocalizador;
    public javax.swing.JLabel lblEstatusPersona2;
    public javax.swing.JLabel lblInfoTipoLocalizador;
    public javax.swing.JLabel lblTitlePersona2;
    public javax.swing.JPanel pnlUser3;
    public javax.swing.JTextField txtCodigoTipoLocalizador;
    public javax.swing.JTextField txtDescripccionTipoLocalizador;
    // End of variables declaration//GEN-END:variables
}
