/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TRANSPORTE.VISTAS.UNIDADES;

/**
 *
 * @author milag
 */
public class formCarga extends javax.swing.JPanel {

    /**
     * Creates new form formCarga
     */
    public formCarga() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUser1 = new javax.swing.JPanel();
        lblTitlePersona = new javax.swing.JLabel();
        lblEstatusPersona = new javax.swing.JLabel();
        lblCombreCarga = new javax.swing.JLabel();
        txtNombreCarga = new javax.swing.JTextField();
        lblCodigoCarga = new javax.swing.JLabel();
        txtCodigoCarga = new javax.swing.JTextField();
        txtCapacidadCarga = new javax.swing.JTextField();
        lblCapacidad = new javax.swing.JLabel();
        lblInfoCarga = new javax.swing.JLabel();
        lblDescripccionCarga = new javax.swing.JLabel();
        txtDescripccionCarga = new javax.swing.JTextField();
        btnCancelFormCarga = new javax.swing.JButton();
        btnCleanFormCarga = new javax.swing.JButton();
        btnSetFormCarga = new javax.swing.JButton();
        btnBuscarCarga = new javax.swing.JButton();
        btnEliminarFormCarga = new javax.swing.JButton();

        pnlUser1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitlePersona.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitlePersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePersona.setText("TIPO DE CARGA");

        lblEstatusPersona.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblEstatusPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstatusPersona.setText("0");
        lblEstatusPersona.setEnabled(false);

        lblCombreCarga.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCombreCarga.setText("NOMBRE");

        txtNombreCarga.setBackground(new java.awt.Color(250, 250, 250));
        txtNombreCarga.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtNombreCarga.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreCarga.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombreCarga.setOpaque(true);

        lblCodigoCarga.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCodigoCarga.setText("CODIGO");

        txtCodigoCarga.setBackground(new java.awt.Color(250, 250, 250));
        txtCodigoCarga.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtCodigoCarga.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCodigoCarga.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigoCarga.setOpaque(true);

        txtCapacidadCarga.setBackground(new java.awt.Color(250, 250, 250));
        txtCapacidadCarga.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtCapacidadCarga.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCapacidadCarga.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCapacidadCarga.setOpaque(true);

        lblCapacidad.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCapacidad.setText("CAPACIDAD");

        lblInfoCarga.setForeground(new java.awt.Color(255, 0, 51));
        lblInfoCarga.setText("* ");

        lblDescripccionCarga.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblDescripccionCarga.setText("DESCRIPCCION");

        txtDescripccionCarga.setBackground(new java.awt.Color(250, 250, 250));
        txtDescripccionCarga.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtDescripccionCarga.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescripccionCarga.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDescripccionCarga.setOpaque(true);

        btnCancelFormCarga.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelFormCarga.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelFormCarga.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelFormCarga.setText("CANCELAR");
        btnCancelFormCarga.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelFormCarga.setIconTextGap(10);
        btnCancelFormCarga.setMargin(new java.awt.Insets(2, 1, 3, 14));

        btnCleanFormCarga.setBackground(new java.awt.Color(230, 230, 230));
        btnCleanFormCarga.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCleanFormCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMop.png"))); // NOI18N
        btnCleanFormCarga.setText("LIMPIAR");
        btnCleanFormCarga.setToolTipText("");
        btnCleanFormCarga.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCleanFormCarga.setIconTextGap(10);
        btnCleanFormCarga.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCleanFormCarga.setMaximumSize(new java.awt.Dimension(125, 35));
        btnCleanFormCarga.setMinimumSize(new java.awt.Dimension(125, 35));
        btnCleanFormCarga.setPreferredSize(new java.awt.Dimension(125, 35));

        btnSetFormCarga.setBackground(new java.awt.Color(153, 255, 153));
        btnSetFormCarga.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSetFormCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnSetFormCarga.setText("REGISTRAR");
        btnSetFormCarga.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSetFormCarga.setIconTextGap(10);
        btnSetFormCarga.setMargin(new java.awt.Insets(0, 0, 0, 0));

        btnBuscarCarga.setBackground(new java.awt.Color(231, 255, 255));
        btnBuscarCarga.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnBuscarCarga.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnBuscarCarga.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBuscarCarga.setIconTextGap(10);
        btnBuscarCarga.setMargin(new java.awt.Insets(0, 0, 0, 0));

        btnEliminarFormCarga.setBackground(new java.awt.Color(102, 0, 0));
        btnEliminarFormCarga.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEliminarFormCarga.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarFormCarga.setText("ELIMINAR");
        btnEliminarFormCarga.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminarFormCarga.setIconTextGap(10);
        btnEliminarFormCarga.setMargin(new java.awt.Insets(2, 1, 3, 14));

        javax.swing.GroupLayout pnlUser1Layout = new javax.swing.GroupLayout(pnlUser1);
        pnlUser1.setLayout(pnlUser1Layout);
        pnlUser1Layout.setHorizontalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUser1Layout.createSequentialGroup()
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                .addComponent(lblCapacidad)
                                .addGap(20, 20, 20)
                                .addComponent(txtCapacidadCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblDescripccionCarga))
                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                .addComponent(lblCodigoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarCarga)
                                .addGap(2, 2, 2)
                                .addComponent(txtCodigoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblCombreCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombreCarga, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(txtDescripccionCarga)))
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addComponent(lblEstatusPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTitlePersona, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                            .addComponent(lblInfoCarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlUser1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(btnCancelFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(btnCleanFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(btnEliminarFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58)
                .addComponent(btnSetFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        pnlUser1Layout.setVerticalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                .addComponent(lblTitlePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstatusPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigoCarga)
                        .addComponent(txtCodigoCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCombreCarga)
                        .addComponent(txtNombreCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCapacidadCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCapacidad)
                    .addComponent(lblDescripccionCarga)
                    .addComponent(txtDescripccionCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCleanFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetFormCarga, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarCarga;
    public javax.swing.JButton btnCancelFormCarga;
    public javax.swing.JButton btnCleanFormCarga;
    public javax.swing.JButton btnEliminarFormCarga;
    public javax.swing.JButton btnSetFormCarga;
    public javax.swing.JLabel lblCapacidad;
    public javax.swing.JLabel lblCodigoCarga;
    public javax.swing.JLabel lblCombreCarga;
    public javax.swing.JLabel lblDescripccionCarga;
    public javax.swing.JLabel lblEstatusPersona;
    public javax.swing.JLabel lblInfoCarga;
    public javax.swing.JLabel lblTitlePersona;
    public javax.swing.JPanel pnlUser1;
    public javax.swing.JTextField txtCapacidadCarga;
    public javax.swing.JTextField txtCodigoCarga;
    public javax.swing.JTextField txtDescripccionCarga;
    public javax.swing.JTextField txtNombreCarga;
    // End of variables declaration//GEN-END:variables
}
