/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TRANSPORTE.VISTAS.UNIDADES;

/**
 *
 * @author milag
 */
public class formLocalizador extends javax.swing.JPanel {

    /**
     * Creates new form formLocalizador
     */
    public formLocalizador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUser3 = new javax.swing.JPanel();
        lblTitlePersona2 = new javax.swing.JLabel();
        lblEstatusPersona2 = new javax.swing.JLabel();
        lblCodigoLocali = new javax.swing.JLabel();
        txtCodigoLocali = new javax.swing.JTextField();
        lblCapacidad = new javax.swing.JLabel();
        lblInfoLocalizador = new javax.swing.JLabel();
        lblDescripccionCarga = new javax.swing.JLabel();
        txtDescripccionLocali = new javax.swing.JTextField();
        btnCancelFormLocalizador = new javax.swing.JButton();
        btnCleanFormLocalizador = new javax.swing.JButton();
        btnSetFormTipoLocalizador = new javax.swing.JButton();
        btnBuscarLocali = new javax.swing.JButton();
        btnEliminarFormLocalizador = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnSetFormLocali = new javax.swing.JButton();

        pnlUser3.setBackground(new java.awt.Color(255, 255, 255));

        lblTitlePersona2.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitlePersona2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePersona2.setText("LOCALIZADOR");

        lblEstatusPersona2.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblEstatusPersona2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstatusPersona2.setText("0");
        lblEstatusPersona2.setEnabled(false);

        lblCodigoLocali.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCodigoLocali.setText("CODIGO");

        txtCodigoLocali.setBackground(new java.awt.Color(250, 250, 250));
        txtCodigoLocali.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtCodigoLocali.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCodigoLocali.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigoLocali.setOpaque(true);

        lblCapacidad.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCapacidad.setText("TIPO");

        lblInfoLocalizador.setForeground(new java.awt.Color(255, 0, 51));
        lblInfoLocalizador.setText("* ");

        lblDescripccionCarga.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblDescripccionCarga.setText("DESCRIPCCION");

        txtDescripccionLocali.setBackground(new java.awt.Color(250, 250, 250));
        txtDescripccionLocali.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtDescripccionLocali.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescripccionLocali.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDescripccionLocali.setOpaque(true);

        btnCancelFormLocalizador.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelFormLocalizador.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelFormLocalizador.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelFormLocalizador.setText("CANCELAR");
        btnCancelFormLocalizador.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelFormLocalizador.setIconTextGap(10);
        btnCancelFormLocalizador.setMargin(new java.awt.Insets(2, 1, 3, 14));

        btnCleanFormLocalizador.setBackground(new java.awt.Color(230, 230, 230));
        btnCleanFormLocalizador.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCleanFormLocalizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMop.png"))); // NOI18N
        btnCleanFormLocalizador.setText("LIMPIAR");
        btnCleanFormLocalizador.setToolTipText("");
        btnCleanFormLocalizador.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCleanFormLocalizador.setIconTextGap(10);
        btnCleanFormLocalizador.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCleanFormLocalizador.setMaximumSize(new java.awt.Dimension(125, 35));
        btnCleanFormLocalizador.setMinimumSize(new java.awt.Dimension(125, 35));
        btnCleanFormLocalizador.setPreferredSize(new java.awt.Dimension(125, 35));

        btnSetFormTipoLocalizador.setBackground(new java.awt.Color(153, 255, 153));
        btnSetFormTipoLocalizador.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSetFormTipoLocalizador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnSetFormTipoLocalizador.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSetFormTipoLocalizador.setIconTextGap(10);
        btnSetFormTipoLocalizador.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnSetFormTipoLocalizador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetFormTipoLocalizadorActionPerformed(evt);
            }
        });

        btnBuscarLocali.setBackground(new java.awt.Color(231, 255, 255));
        btnBuscarLocali.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnBuscarLocali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnBuscarLocali.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnBuscarLocali.setIconTextGap(10);
        btnBuscarLocali.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnBuscarLocali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarLocaliActionPerformed(evt);
            }
        });

        btnEliminarFormLocalizador.setBackground(new java.awt.Color(102, 0, 0));
        btnEliminarFormLocalizador.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEliminarFormLocalizador.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarFormLocalizador.setText("ELIMINAR");
        btnEliminarFormLocalizador.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminarFormLocalizador.setIconTextGap(10);
        btnEliminarFormLocalizador.setMargin(new java.awt.Insets(2, 1, 3, 14));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnSetFormLocali.setBackground(new java.awt.Color(153, 255, 153));
        btnSetFormLocali.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSetFormLocali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnSetFormLocali.setText("REGISTRAR");
        btnSetFormLocali.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSetFormLocali.setIconTextGap(10);
        btnSetFormLocali.setMargin(new java.awt.Insets(0, 0, 0, 0));

        javax.swing.GroupLayout pnlUser3Layout = new javax.swing.GroupLayout(pnlUser3);
        pnlUser3.setLayout(pnlUser3Layout);
        pnlUser3Layout.setHorizontalGroup(
            pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUser3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlUser3Layout.createSequentialGroup()
                            .addComponent(lblCodigoLocali, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnBuscarLocali))
                        .addComponent(btnCancelFormLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addComponent(lblCapacidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSetFormTipoLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jComboBox1, 0, 180, Short.MAX_VALUE)
                            .addComponent(txtCodigoLocali))
                        .addGap(18, 18, 18)
                        .addComponent(lblDescripccionCarga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripccionLocali, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnCleanFormLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnEliminarFormLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(btnSetFormLocali, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(pnlUser3Layout.createSequentialGroup()
                .addComponent(lblEstatusPersona2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitlePersona2, javax.swing.GroupLayout.DEFAULT_SIZE, 705, Short.MAX_VALUE)
                    .addComponent(lblInfoLocalizador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUser3Layout.setVerticalGroup(
            pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser3Layout.createSequentialGroup()
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addComponent(lblTitlePersona2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblInfoLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstatusPersona2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlUser3Layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblCodigoLocali)
                                        .addComponent(txtCodigoLocali, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnBuscarLocali, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtDescripccionLocali, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblDescripccionCarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCapacidad)
                    .addComponent(btnSetFormTipoLocalizador)
                    .addComponent(jComboBox1))
                .addGap(43, 43, 43)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCleanFormLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelFormLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarFormLocalizador, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetFormLocali, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarLocaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarLocaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarLocaliActionPerformed

    private void btnSetFormTipoLocalizadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetFormTipoLocalizadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSetFormTipoLocalizadorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarLocali;
    public javax.swing.JButton btnCancelFormLocalizador;
    public javax.swing.JButton btnCleanFormLocalizador;
    public javax.swing.JButton btnEliminarFormLocalizador;
    public javax.swing.JButton btnSetFormLocali;
    public javax.swing.JButton btnSetFormTipoLocalizador;
    private javax.swing.JComboBox<String> jComboBox1;
    public javax.swing.JLabel lblCapacidad;
    public javax.swing.JLabel lblCodigoLocali;
    public javax.swing.JLabel lblDescripccionCarga;
    public javax.swing.JLabel lblEstatusPersona2;
    public javax.swing.JLabel lblInfoLocalizador;
    public javax.swing.JLabel lblTitlePersona2;
    public javax.swing.JPanel pnlUser3;
    public javax.swing.JTextField txtCodigoLocali;
    public javax.swing.JTextField txtDescripccionLocali;
    // End of variables declaration//GEN-END:variables
}
