/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TRANSPORTE.VISTAS.UNIDADES;

/**
 *
 * @author arnal
 */
public class formUnidades extends javax.swing.JFrame {

    /**
     * Creates new form formPersonas
     */
    public formUnidades() {
        initComponents();
        lblControlFormPersona.setVisible(false);
        lblEstatusPersona.setVisible(false);
        lblEstatusPersona1.setVisible(false);
        lblInfoPersona.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUser1 = new javax.swing.JPanel();
        lblTitlePersona = new javax.swing.JLabel();
        lblEstatusPersona = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtNombrePersona = new javax.swing.JTextField();
        lblCedula3 = new javax.swing.JLabel();
        txtDocumentoPersona = new javax.swing.JTextField();
        txtTelefonoPersona = new javax.swing.JTextField();
        lblCategoria1 = new javax.swing.JLabel();
        lblInfoPersona = new javax.swing.JLabel();
        lblControlFormPersona = new javax.swing.JLabel();
        lblCategoria6 = new javax.swing.JLabel();
        txtCorreoPersona = new javax.swing.JTextField();
        btnCancelFormPersona = new javax.swing.JButton();
        btnCleanFormPersona = new javax.swing.JButton();
        btnSetFormPersona = new javax.swing.JButton();
        lblCategoria2 = new javax.swing.JLabel();
        txtTelefonoPersona1 = new javax.swing.JTextField();
        lblCategoria3 = new javax.swing.JLabel();
        txtTelefonoPersona2 = new javax.swing.JTextField();
        lblCategoria7 = new javax.swing.JLabel();
        jcbxTipoPersona = new javax.swing.JComboBox<>();
        lblCategoria9 = new javax.swing.JLabel();
        jcbxTipoPersona1 = new javax.swing.JComboBox<>();
        btnSetFormPersona4 = new javax.swing.JButton();
        lblCedula4 = new javax.swing.JLabel();
        txtDocumentoPersona5 = new javax.swing.JTextField();
        lblNombre3 = new javax.swing.JLabel();
        txtNombrePersona4 = new javax.swing.JTextField();
        btnSetFormPersona3 = new javax.swing.JButton();
        lblCedula6 = new javax.swing.JLabel();
        txtDocumentoPersona3 = new javax.swing.JTextField();
        lblEstatusPersona1 = new javax.swing.JLabel();

        pnlUser1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitlePersona.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitlePersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePersona.setText("REGISTRAR UNIDADES");

        lblEstatusPersona.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblEstatusPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstatusPersona.setText("0");
        lblEstatusPersona.setEnabled(false);

        lblNombre1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblNombre1.setText("MARCA");

        txtNombrePersona.setBackground(new java.awt.Color(250, 250, 250));
        txtNombrePersona.setForeground(new java.awt.Color(0, 0, 0));
        txtNombrePersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtNombrePersona.setCaretColor(new java.awt.Color(0, 0, 0));
        txtNombrePersona.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombrePersona.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombrePersona.setOpaque(true);

        lblCedula3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCedula3.setText("PLACA");

        txtDocumentoPersona.setBackground(new java.awt.Color(250, 250, 250));
        txtDocumentoPersona.setForeground(new java.awt.Color(0, 0, 0));
        txtDocumentoPersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtDocumentoPersona.setCaretColor(new java.awt.Color(0, 0, 0));
        txtDocumentoPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDocumentoPersona.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDocumentoPersona.setOpaque(true);

        txtTelefonoPersona.setBackground(new java.awt.Color(250, 250, 250));
        txtTelefonoPersona.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefonoPersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtTelefonoPersona.setCaretColor(new java.awt.Color(0, 0, 0));
        txtTelefonoPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTelefonoPersona.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTelefonoPersona.setOpaque(true);

        lblCategoria1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria1.setText("MODELO");

        lblInfoPersona.setForeground(new java.awt.Color(255, 0, 51));
        lblInfoPersona.setText("* ");

        lblControlFormPersona.setText("1");

        lblCategoria6.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria6.setText("AÑO");

        txtCorreoPersona.setBackground(new java.awt.Color(250, 250, 250));
        txtCorreoPersona.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreoPersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtCorreoPersona.setCaretColor(new java.awt.Color(0, 0, 0));
        txtCorreoPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCorreoPersona.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCorreoPersona.setOpaque(true);

        btnCancelFormPersona.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelFormPersona.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelFormPersona.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelFormPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ligth/iconTrash.png"))); // NOI18N
        btnCancelFormPersona.setText("CANCELAR");
        btnCancelFormPersona.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelFormPersona.setIconTextGap(10);
        btnCancelFormPersona.setMargin(new java.awt.Insets(2, 1, 3, 14));

        btnCleanFormPersona.setBackground(new java.awt.Color(230, 230, 230));
        btnCleanFormPersona.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCleanFormPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMop.png"))); // NOI18N
        btnCleanFormPersona.setText("LIMPIAR");
        btnCleanFormPersona.setToolTipText("");
        btnCleanFormPersona.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCleanFormPersona.setIconTextGap(10);
        btnCleanFormPersona.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCleanFormPersona.setMaximumSize(new java.awt.Dimension(125, 35));
        btnCleanFormPersona.setMinimumSize(new java.awt.Dimension(125, 35));
        btnCleanFormPersona.setPreferredSize(new java.awt.Dimension(125, 35));

        btnSetFormPersona.setBackground(new java.awt.Color(153, 255, 153));
        btnSetFormPersona.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSetFormPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnSetFormPersona.setText("REGISTRAR");
        btnSetFormPersona.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSetFormPersona.setIconTextGap(10);
        btnSetFormPersona.setMargin(new java.awt.Insets(0, 0, 0, 0));

        lblCategoria2.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria2.setText("COLOR");

        txtTelefonoPersona1.setBackground(new java.awt.Color(250, 250, 250));
        txtTelefonoPersona1.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefonoPersona1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtTelefonoPersona1.setCaretColor(new java.awt.Color(0, 0, 0));
        txtTelefonoPersona1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTelefonoPersona1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTelefonoPersona1.setOpaque(true);

        lblCategoria3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria3.setText("CAPACIDAD");

        txtTelefonoPersona2.setBackground(new java.awt.Color(250, 250, 250));
        txtTelefonoPersona2.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefonoPersona2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtTelefonoPersona2.setCaretColor(new java.awt.Color(0, 0, 0));
        txtTelefonoPersona2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTelefonoPersona2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTelefonoPersona2.setOpaque(true);

        lblCategoria7.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblCategoria7.setText("TIPO DE CARGA");

        jcbxTipoPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PERSONAS", "ANIMALES", "VARIOS SOLIDOS", "VARIOS A GRANEL", "VARIOS LIQUIDOS", "VARIOS GASEOSOS" }));
        jcbxTipoPersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblCategoria9.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblCategoria9.setText("TIPO DE UNIDAD");

        jcbxTipoPersona1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TERRESTRE", "AEREA", "MARITIMA" }));
        jcbxTipoPersona1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        btnSetFormPersona4.setBackground(new java.awt.Color(231, 255, 255));
        btnSetFormPersona4.setFont(new java.awt.Font("Roboto", 1, 10)); // NOI18N
        btnSetFormPersona4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSetFormPersona4.setText("PROPIETARIO");
        btnSetFormPersona4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSetFormPersona4.setIconTextGap(10);
        btnSetFormPersona4.setMargin(new java.awt.Insets(0, 0, 0, 0));

        lblCedula4.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblCedula4.setText("CEDULA");

        txtDocumentoPersona5.setEditable(false);
        txtDocumentoPersona5.setBackground(new java.awt.Color(250, 250, 250));
        txtDocumentoPersona5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtDocumentoPersona5.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDocumentoPersona5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDocumentoPersona5.setEnabled(false);
        txtDocumentoPersona5.setOpaque(true);

        lblNombre3.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblNombre3.setText("CLIENTE");

        txtNombrePersona4.setEditable(false);
        txtNombrePersona4.setBackground(new java.awt.Color(250, 250, 250));
        txtNombrePersona4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtNombrePersona4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombrePersona4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombrePersona4.setEnabled(false);
        txtNombrePersona4.setOpaque(true);

        btnSetFormPersona3.setBackground(new java.awt.Color(231, 255, 255));
        btnSetFormPersona3.setFont(new java.awt.Font("Roboto", 1, 11)); // NOI18N
        btnSetFormPersona3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnSetFormPersona3.setText("LOCALIZADOR");
        btnSetFormPersona3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSetFormPersona3.setIconTextGap(2);
        btnSetFormPersona3.setInheritsPopupMenu(true);
        btnSetFormPersona3.setMargin(new java.awt.Insets(0, 0, 0, 0));

        lblCedula6.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        lblCedula6.setText("LOCALIZADOR");

        txtDocumentoPersona3.setEditable(false);
        txtDocumentoPersona3.setBackground(new java.awt.Color(250, 250, 250));
        txtDocumentoPersona3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtDocumentoPersona3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDocumentoPersona3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDocumentoPersona3.setEnabled(false);
        txtDocumentoPersona3.setOpaque(true);

        lblEstatusPersona1.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblEstatusPersona1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstatusPersona1.setText("0");
        lblEstatusPersona1.setEnabled(false);

        javax.swing.GroupLayout pnlUser1Layout = new javax.swing.GroupLayout(pnlUser1);
        pnlUser1.setLayout(pnlUser1Layout);
        pnlUser1Layout.setHorizontalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUser1Layout.createSequentialGroup()
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(lblControlFormPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addContainerGap(424, Short.MAX_VALUE)
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                                .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtCorreoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCategoria6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCategoria7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCedula6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTelefonoPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtDocumentoPersona3, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                        .addComponent(jcbxTipoPersona, 0, 180, Short.MAX_VALUE)
                                        .addComponent(txtTelefonoPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))))
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUser1Layout.createSequentialGroup()
                                .addComponent(btnCancelFormPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addComponent(btnCleanFormPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblCedula3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblCedula4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblNombre3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(btnSetFormPersona4, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblCategoria1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCategoria9, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDocumentoPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtNombrePersona, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(jcbxTipoPersona1, javax.swing.GroupLayout.Alignment.TRAILING, 0, 180, Short.MAX_VALUE)
                                    .addComponent(txtTelefonoPersona2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtDocumentoPersona5, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                    .addComponent(txtNombrePersona4, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                                .addComponent(btnSetFormPersona3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(181, 181, 181))
                            .addComponent(btnSetFormPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57))
            .addGroup(pnlUser1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitlePersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addComponent(lblEstatusPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstatusPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98)
                        .addComponent(lblInfoPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(33, 33, 33))
        );
        pnlUser1Layout.setVerticalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                .addComponent(lblControlFormPersona)
                .addGap(9, 9, 9)
                .addComponent(lblTitlePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEstatusPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblEstatusPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                        .addComponent(lblInfoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDocumentoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCorreoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblNombre1))
                                .addGap(53, 53, 53)
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTelefonoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCategoria1)
                                    .addComponent(lblCategoria6))
                                .addGap(47, 47, 47)
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTelefonoPersona2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCategoria3)
                                    .addComponent(txtTelefonoPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCategoria2))
                                .addGap(46, 46, 46)
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jcbxTipoPersona1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbxTipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCategoria9)
                                    .addComponent(lblCategoria7))
                                .addGap(100, 100, 100)
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDocumentoPersona5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDocumentoPersona3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCedula4)
                                    .addComponent(lblCedula6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                .addGap(279, 279, 279)
                                .addComponent(btnSetFormPersona3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombrePersona4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNombre3))
                        .addGap(0, 40, Short.MAX_VALUE)
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCleanFormPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelFormPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSetFormPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addComponent(lblCedula3)
                        .addGap(262, 262, 262)
                        .addComponent(btnSetFormPersona4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlUser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelFormPersona;
    public javax.swing.JButton btnCleanFormPersona;
    public javax.swing.JButton btnSetFormPersona;
    public javax.swing.JButton btnSetFormPersona3;
    public javax.swing.JButton btnSetFormPersona4;
    public javax.swing.JComboBox<String> jcbxTipoPersona;
    public javax.swing.JComboBox<String> jcbxTipoPersona1;
    public javax.swing.JLabel lblCategoria1;
    public javax.swing.JLabel lblCategoria2;
    public javax.swing.JLabel lblCategoria3;
    public javax.swing.JLabel lblCategoria6;
    public javax.swing.JLabel lblCategoria7;
    public javax.swing.JLabel lblCategoria9;
    public javax.swing.JLabel lblCedula3;
    public javax.swing.JLabel lblCedula4;
    public javax.swing.JLabel lblCedula6;
    public javax.swing.JLabel lblControlFormPersona;
    public javax.swing.JLabel lblEstatusPersona;
    public javax.swing.JLabel lblEstatusPersona1;
    public javax.swing.JLabel lblInfoPersona;
    public javax.swing.JLabel lblNombre1;
    public javax.swing.JLabel lblNombre3;
    public javax.swing.JLabel lblTitlePersona;
    public javax.swing.JPanel pnlUser1;
    public javax.swing.JTextField txtCorreoPersona;
    public javax.swing.JTextField txtDocumentoPersona;
    public javax.swing.JTextField txtDocumentoPersona3;
    public javax.swing.JTextField txtDocumentoPersona5;
    public javax.swing.JTextField txtNombrePersona;
    public javax.swing.JTextField txtNombrePersona4;
    public javax.swing.JTextField txtTelefonoPersona;
    public javax.swing.JTextField txtTelefonoPersona1;
    public javax.swing.JTextField txtTelefonoPersona2;
    // End of variables declaration//GEN-END:variables
}
