/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TRANSPORTE.VISTAS.UNIDADES;

/**
 *
 * @author milag
 */
public class formMantenimiento extends javax.swing.JFrame {

    /**
     * Creates new form formMantenimiento
     */
    public formMantenimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitleMantemimiento = new javax.swing.JLabel();
        subMain1 = new javax.swing.JPanel();
        checkEstadoMantenimiento = new javax.swing.JCheckBox();
        btnModificarMantenimiento = new javax.swing.JButton();
        btnDeleteFromMantenimiento = new javax.swing.JButton();
        btnFormRegistraMantenimiento = new javax.swing.JButton();
        txtFilterUnidad = new javax.swing.JTextField();
        btnSearchUnidadMant = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblUnidadesMantenimiento = new javax.swing.JTable();
        btnTiposMante = new javax.swing.JToggleButton();
        btnMecanicos = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitleMantemimiento.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitleMantemimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleMantemimiento.setText("MANTENIMIENTO");

        subMain1.setBackground(new java.awt.Color(255, 255, 255));
        subMain1.setMinimumSize(new java.awt.Dimension(684, 685));
        subMain1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkEstadoMantenimiento.setText("NO FINALIZADOS");
        subMain1.add(checkEstadoMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnModificarMantenimiento.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnModificarMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTableEdit.png"))); // NOI18N
        btnModificarMantenimiento.setText("MODIFICAR");
        btnModificarMantenimiento.setToolTipText("");
        btnModificarMantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarMantenimiento.setIconTextGap(10);
        btnModificarMantenimiento.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnModificarMantenimiento.setMaximumSize(new java.awt.Dimension(125, 35));
        btnModificarMantenimiento.setMinimumSize(new java.awt.Dimension(125, 35));
        btnModificarMantenimiento.setPreferredSize(new java.awt.Dimension(125, 35));
        subMain1.add(btnModificarMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 160, 40));

        btnDeleteFromMantenimiento.setBackground(new java.awt.Color(102, 0, 0));
        btnDeleteFromMantenimiento.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDeleteFromMantenimiento.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFromMantenimiento.setText("ELIMINAR");
        btnDeleteFromMantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDeleteFromMantenimiento.setIconTextGap(10);
        btnDeleteFromMantenimiento.setMargin(new java.awt.Insets(2, 1, 3, 14));
        subMain1.add(btnDeleteFromMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, 160, 40));

        btnFormRegistraMantenimiento.setBackground(new java.awt.Color(153, 255, 153));
        btnFormRegistraMantenimiento.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnFormRegistraMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnFormRegistraMantenimiento.setText("<html>REGISTAR<br>MANTENIMIENTO</html>");
        btnFormRegistraMantenimiento.setToolTipText("");
        btnFormRegistraMantenimiento.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFormRegistraMantenimiento.setIconTextGap(10);
        btnFormRegistraMantenimiento.setMargin(new java.awt.Insets(2, 1, 3, 14));
        subMain1.add(btnFormRegistraMantenimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 160, 60));

        txtFilterUnidad.setBackground(new java.awt.Color(242, 242, 242));
        txtFilterUnidad.setBorder(null);
        txtFilterUnidad.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtFilterUnidad.setOpaque(true);
        subMain1.add(txtFilterUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 40));

        btnSearchUnidadMant.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearchUnidadMant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearchUnidadMant.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchUnidadMant.setOpaque(true);
        subMain1.add(btnSearchUnidadMant, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 40, 40));

        tblUnidadesMantenimiento.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tblUnidadesMantenimiento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblUnidadesMantenimiento.setRowHeight(35);
        jScrollPane4.setViewportView(tblUnidadesMantenimiento);

        subMain1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 980, 410));

        btnTiposMante.setBackground(new java.awt.Color(248, 248, 248));
        btnTiposMante.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnTiposMante.setText("<html>TIPOS DE <br> MANTENIMIENTO </html>");
        btnTiposMante.setBorder(null);
        btnTiposMante.setBorderPainted(false);
        btnTiposMante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subMain1.add(btnTiposMante, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 160, 60));

        btnMecanicos.setBackground(new java.awt.Color(248, 248, 248));
        btnMecanicos.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnMecanicos.setText("<html>MECANICOS</html>");
        btnMecanicos.setBorder(null);
        btnMecanicos.setBorderPainted(false);
        btnMecanicos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subMain1.add(btnMecanicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 150, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleMantemimiento, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(subMain1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitleMantemimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(subMain1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDeleteFromMantenimiento;
    public javax.swing.JButton btnFormRegistraMantenimiento;
    public javax.swing.JToggleButton btnMecanicos;
    public javax.swing.JButton btnModificarMantenimiento;
    private javax.swing.JLabel btnSearchUnidadMant;
    public javax.swing.JToggleButton btnTiposMante;
    public javax.swing.JCheckBox checkEstadoMantenimiento;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JLabel lblTitleMantemimiento;
    public javax.swing.JPanel subMain1;
    public javax.swing.JTable tblUnidadesMantenimiento;
    public javax.swing.JTextField txtFilterUnidad;
    // End of variables declaration//GEN-END:variables
}
