/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TRANSPORTE.VISTAS.UNIDADES;

/**
 *
 * @author milag
 */
public class formTipoMantenimiento extends javax.swing.JFrame {

    /**
     * Creates new form formTipoMantenimiento
     */
    public formTipoMantenimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUser1 = new javax.swing.JPanel();
        lblNombreMecanico = new javax.swing.JLabel();
        txtNombreTipoMant = new javax.swing.JTextField();
        lblCodigoTipoMant = new javax.swing.JLabel();
        txtCodigoTipoMant = new javax.swing.JTextField();
        txtDescripcionTIpoMant = new javax.swing.JTextField();
        lblDescripMant = new javax.swing.JLabel();
        lblInfoTipoMantenimiento = new javax.swing.JLabel();
        btnCancelFormTipoMante = new javax.swing.JButton();
        btnCleanFormTipoMante = new javax.swing.JButton();
        btnSetFormTipoMante = new javax.swing.JButton();
        lblTitleMantemimiento = new javax.swing.JLabel();
        btnEliminarFormMante = new javax.swing.JButton();
        btnSearchTipoMante = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlUser1.setBackground(new java.awt.Color(255, 255, 255));

        lblNombreMecanico.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblNombreMecanico.setText("NOMBRE");

        txtNombreTipoMant.setBackground(new java.awt.Color(250, 250, 250));
        txtNombreTipoMant.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtNombreTipoMant.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreTipoMant.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombreTipoMant.setOpaque(true);

        lblCodigoTipoMant.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCodigoTipoMant.setText("CODIGO");

        txtCodigoTipoMant.setBackground(new java.awt.Color(250, 250, 250));
        txtCodigoTipoMant.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtCodigoTipoMant.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCodigoTipoMant.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigoTipoMant.setOpaque(true);

        txtDescripcionTIpoMant.setBackground(new java.awt.Color(250, 250, 250));
        txtDescripcionTIpoMant.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtDescripcionTIpoMant.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescripcionTIpoMant.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDescripcionTIpoMant.setOpaque(true);

        lblDescripMant.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblDescripMant.setText("DESCRIPCION");

        lblInfoTipoMantenimiento.setForeground(new java.awt.Color(255, 0, 51));
        lblInfoTipoMantenimiento.setText("* ");

        btnCancelFormTipoMante.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelFormTipoMante.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelFormTipoMante.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelFormTipoMante.setText("CANCELAR");
        btnCancelFormTipoMante.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelFormTipoMante.setIconTextGap(10);
        btnCancelFormTipoMante.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCancelFormTipoMante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelFormTipoManteActionPerformed(evt);
            }
        });

        btnCleanFormTipoMante.setBackground(new java.awt.Color(230, 230, 230));
        btnCleanFormTipoMante.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCleanFormTipoMante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMop.png"))); // NOI18N
        btnCleanFormTipoMante.setText("LIMPIAR");
        btnCleanFormTipoMante.setToolTipText("");
        btnCleanFormTipoMante.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCleanFormTipoMante.setIconTextGap(10);
        btnCleanFormTipoMante.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCleanFormTipoMante.setMaximumSize(new java.awt.Dimension(125, 35));
        btnCleanFormTipoMante.setMinimumSize(new java.awt.Dimension(125, 35));
        btnCleanFormTipoMante.setPreferredSize(new java.awt.Dimension(125, 35));

        btnSetFormTipoMante.setBackground(new java.awt.Color(153, 255, 153));
        btnSetFormTipoMante.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSetFormTipoMante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnSetFormTipoMante.setText("REGISTRAR");
        btnSetFormTipoMante.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSetFormTipoMante.setIconTextGap(10);
        btnSetFormTipoMante.setMargin(new java.awt.Insets(0, 0, 0, 0));

        lblTitleMantemimiento.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitleMantemimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleMantemimiento.setText("TIPO DE MANTENIMIENTO");

        btnEliminarFormMante.setBackground(new java.awt.Color(102, 0, 0));
        btnEliminarFormMante.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEliminarFormMante.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarFormMante.setText("ELIMINAR");
        btnEliminarFormMante.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminarFormMante.setIconTextGap(10);
        btnEliminarFormMante.setMargin(new java.awt.Insets(2, 1, 3, 14));

        btnSearchTipoMante.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearchTipoMante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearchTipoMante.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchTipoMante.setOpaque(true);

        javax.swing.GroupLayout pnlUser1Layout = new javax.swing.GroupLayout(pnlUser1);
        pnlUser1.setLayout(pnlUser1Layout);
        pnlUser1Layout.setHorizontalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUser1Layout.createSequentialGroup()
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfoTipoMantenimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitleMantemimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblDescripMant)
                                        .addGroup(pnlUser1Layout.createSequentialGroup()
                                            .addComponent(lblCodigoTipoMant, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnSearchTipoMante)))
                                    .addComponent(btnCancelFormTipoMante, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtDescripcionTIpoMant, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                            .addComponent(txtCodigoTipoMant))
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                                        .addComponent(btnCleanFormTipoMante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)))
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlUser1Layout.createSequentialGroup()
                                        .addComponent(lblNombreMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(14, 14, 14)
                                        .addComponent(txtNombreTipoMant, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlUser1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(btnEliminarFormMante, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(34, 34, 34)
                                        .addComponent(btnSetFormTipoMante, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlUser1Layout.setVerticalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleMantemimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoTipoMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchTipoMante, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigoTipoMant)
                        .addComponent(txtCodigoTipoMant, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombreMecanico)
                        .addComponent(txtNombreTipoMant, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcionTIpoMant, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripMant))
                .addGap(35, 35, 35)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelFormTipoMante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCleanFormTipoMante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarFormMante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetFormTipoMante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelFormTipoManteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelFormTipoManteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelFormTipoManteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formTipoMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formTipoMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formTipoMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formTipoMantenimiento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formTipoMantenimiento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelFormTipoMante;
    public javax.swing.JButton btnCleanFormTipoMante;
    public javax.swing.JButton btnEliminarFormMante;
    private javax.swing.JLabel btnSearchTipoMante;
    public javax.swing.JButton btnSetFormTipoMante;
    public javax.swing.JLabel lblCodigoTipoMant;
    public javax.swing.JLabel lblDescripMant;
    public javax.swing.JLabel lblInfoTipoMantenimiento;
    public javax.swing.JLabel lblNombreMecanico;
    public javax.swing.JLabel lblTitleMantemimiento;
    public javax.swing.JPanel pnlUser1;
    public javax.swing.JTextField txtCodigoTipoMant;
    public javax.swing.JTextField txtDescripcionTIpoMant;
    public javax.swing.JTextField txtNombreTipoMant;
    // End of variables declaration//GEN-END:variables
}
