/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TRANSPORTE.VISTAS.UNIDADES;

/**
 *
 * @author milag
 */
public class formTipoDeUnidad extends javax.swing.JFrame {

    /**
     * Creates new form formTipoDeUnidad
     */
    public formTipoDeUnidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUser1 = new javax.swing.JPanel();
        lblEstatusTipoUnidad = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtNombreTipoUnidad = new javax.swing.JTextField();
        lblCodigoTipoUnidad = new javax.swing.JLabel();
        txtCodigoTipoUnidad = new javax.swing.JTextField();
        txtDescripcionTipoUnidad = new javax.swing.JTextField();
        lblDescripcionTipoUnidad = new javax.swing.JLabel();
        lblInfoTipoUnidad = new javax.swing.JLabel();
        btnCancelFormTipoUnidad = new javax.swing.JButton();
        btnCleanFormTipoUnidad = new javax.swing.JButton();
        btnSetFormTipoUnidad = new javax.swing.JButton();
        lblTitleTipoUnidad = new javax.swing.JLabel();
        btnSearchTipoUnidad = new javax.swing.JLabel();
        btnCancelFormTipoUnidad1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlUser1.setBackground(new java.awt.Color(255, 255, 255));

        lblEstatusTipoUnidad.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblEstatusTipoUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstatusTipoUnidad.setText("0");
        lblEstatusTipoUnidad.setEnabled(false);

        lblNombre1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblNombre1.setText("NOMBRE");

        txtNombreTipoUnidad.setBackground(new java.awt.Color(250, 250, 250));
        txtNombreTipoUnidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtNombreTipoUnidad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreTipoUnidad.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombreTipoUnidad.setOpaque(true);

        lblCodigoTipoUnidad.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCodigoTipoUnidad.setText("CODIGO");

        txtCodigoTipoUnidad.setBackground(new java.awt.Color(250, 250, 250));
        txtCodigoTipoUnidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtCodigoTipoUnidad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCodigoTipoUnidad.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigoTipoUnidad.setOpaque(true);

        txtDescripcionTipoUnidad.setBackground(new java.awt.Color(250, 250, 250));
        txtDescripcionTipoUnidad.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtDescripcionTipoUnidad.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescripcionTipoUnidad.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDescripcionTipoUnidad.setOpaque(true);

        lblDescripcionTipoUnidad.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblDescripcionTipoUnidad.setText("DESCRIPCION");

        lblInfoTipoUnidad.setForeground(new java.awt.Color(255, 0, 51));
        lblInfoTipoUnidad.setText("* ");

        btnCancelFormTipoUnidad.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelFormTipoUnidad.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelFormTipoUnidad.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelFormTipoUnidad.setText("ELIMINAR");
        btnCancelFormTipoUnidad.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelFormTipoUnidad.setIconTextGap(10);
        btnCancelFormTipoUnidad.setMargin(new java.awt.Insets(2, 1, 3, 14));

        btnCleanFormTipoUnidad.setBackground(new java.awt.Color(230, 230, 230));
        btnCleanFormTipoUnidad.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCleanFormTipoUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMop.png"))); // NOI18N
        btnCleanFormTipoUnidad.setText("LIMPIAR");
        btnCleanFormTipoUnidad.setToolTipText("");
        btnCleanFormTipoUnidad.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCleanFormTipoUnidad.setIconTextGap(10);
        btnCleanFormTipoUnidad.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCleanFormTipoUnidad.setMaximumSize(new java.awt.Dimension(125, 35));
        btnCleanFormTipoUnidad.setMinimumSize(new java.awt.Dimension(125, 35));
        btnCleanFormTipoUnidad.setPreferredSize(new java.awt.Dimension(125, 35));

        btnSetFormTipoUnidad.setBackground(new java.awt.Color(153, 255, 153));
        btnSetFormTipoUnidad.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSetFormTipoUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnSetFormTipoUnidad.setText("REGISTRAR");
        btnSetFormTipoUnidad.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSetFormTipoUnidad.setIconTextGap(10);
        btnSetFormTipoUnidad.setMargin(new java.awt.Insets(0, 0, 0, 0));

        lblTitleTipoUnidad.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitleTipoUnidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleTipoUnidad.setText("TIPO DE UNIDADES");

        btnSearchTipoUnidad.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearchTipoUnidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearchTipoUnidad.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchTipoUnidad.setOpaque(true);

        btnCancelFormTipoUnidad1.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelFormTipoUnidad1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelFormTipoUnidad1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelFormTipoUnidad1.setText("CANCELAR");
        btnCancelFormTipoUnidad1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelFormTipoUnidad1.setIconTextGap(10);
        btnCancelFormTipoUnidad1.setMargin(new java.awt.Insets(2, 1, 3, 14));

        javax.swing.GroupLayout pnlUser1Layout = new javax.swing.GroupLayout(pnlUser1);
        pnlUser1.setLayout(pnlUser1Layout);
        pnlUser1Layout.setHorizontalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUser1Layout.createSequentialGroup()
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEstatusTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)
                        .addComponent(lblInfoTipoUnidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitleTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 734, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDescripcionTipoUnidad)
                                    .addGroup(pnlUser1Layout.createSequentialGroup()
                                        .addComponent(lblCodigoTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addComponent(btnSearchTipoUnidad)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlUser1Layout.createSequentialGroup()
                                        .addComponent(txtCodigoTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(48, 48, 48)
                                        .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombreTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtDescripcionTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(btnCancelFormTipoUnidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCleanFormTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnCancelFormTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(btnSetFormTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addContainerGap())
        );
        pnlUser1Layout.setVerticalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUser1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblInfoTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstatusTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigoTipoUnidad)
                        .addComponent(txtCodigoTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombre1)
                        .addComponent(txtNombreTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSearchTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDescripcionTipoUnidad)
                            .addComponent(txtDescripcionTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelFormTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCleanFormTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSetFormTipoUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCancelFormTipoUnidad1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(64, 64, 64))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formTipoDeUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formTipoDeUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formTipoDeUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formTipoDeUnidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formTipoDeUnidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelFormTipoUnidad;
    public javax.swing.JButton btnCancelFormTipoUnidad1;
    public javax.swing.JButton btnCleanFormTipoUnidad;
    private javax.swing.JLabel btnSearchTipoUnidad;
    public javax.swing.JButton btnSetFormTipoUnidad;
    public javax.swing.JLabel lblCodigoTipoUnidad;
    public javax.swing.JLabel lblDescripcionTipoUnidad;
    public javax.swing.JLabel lblEstatusTipoUnidad;
    public javax.swing.JLabel lblInfoTipoUnidad;
    public javax.swing.JLabel lblNombre1;
    public javax.swing.JLabel lblTitleTipoUnidad;
    public javax.swing.JPanel pnlUser1;
    public javax.swing.JTextField txtCodigoTipoUnidad;
    public javax.swing.JTextField txtDescripcionTipoUnidad;
    public javax.swing.JTextField txtNombreTipoUnidad;
    // End of variables declaration//GEN-END:variables
}
