/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TRANSPORTE.VISTAS.UNIDADES;

/**
 *
 * @author arnal
 */
public class mainUnidades extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */

    public mainUnidades() {
        initComponents();
        btnHeader3.setVisible(false);
        btnHeader4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        btnHeader1 = new javax.swing.JToggleButton();
        btnHeader2 = new javax.swing.JToggleButton();
        btnHeader3 = new javax.swing.JToggleButton();
        btnHeader4 = new javax.swing.JToggleButton();
        pnlMain = new javax.swing.JPanel();
        pnlMain1 = new javax.swing.JPanel();
        checkEstado4 = new javax.swing.JCheckBox();
        btnModificarSede3 = new javax.swing.JButton();
        btnDeleteFromTable1 = new javax.swing.JButton();
        btnFormModifyTransportista1 = new javax.swing.JButton();
        txtFilterSede3 = new javax.swing.JTextField();
        btnSearch4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSedes2 = new javax.swing.JTable();
        checkEstado9 = new javax.swing.JCheckBox();
        btnRecargar1 = new javax.swing.JButton();
        pnlMain2 = new javax.swing.JPanel();
        checkEstado8 = new javax.swing.JCheckBox();
        btnModificarSede7 = new javax.swing.JButton();
        btnDeleteFromTable5 = new javax.swing.JButton();
        btnFormModifyTransportista5 = new javax.swing.JButton();
        txtFilterSede7 = new javax.swing.JTextField();
        btnSearch8 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblSedes6 = new javax.swing.JTable();
        btnRecargar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(684, 694));
        setName("prestamos"); // NOI18N
        setPreferredSize(new java.awt.Dimension(684, 694));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHeader1.setBackground(new java.awt.Color(248, 248, 248));
        btnHeader1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnHeader1.setSelected(true);
        btnHeader1.setText("UNIDADES");
        btnHeader1.setBorder(null);
        btnHeader1.setBorderPainted(false);
        btnHeader1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader.add(btnHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 196, 70));

        btnHeader2.setBackground(new java.awt.Color(248, 248, 248));
        btnHeader2.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        btnHeader2.setText("PROPIETARIOS");
        btnHeader2.setBorder(null);
        btnHeader2.setBorderPainted(false);
        btnHeader2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader.add(btnHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 0, 196, 70));

        btnHeader3.setBackground(new java.awt.Color(248, 248, 248));
        btnHeader3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnHeader3.setText("<html>ENCARGADOS DE<br> MANTENIMIENTO</html>");
        btnHeader3.setBorder(null);
        btnHeader3.setBorderPainted(false);
        btnHeader3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader.add(btnHeader3, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 0, 196, 70));

        btnHeader4.setBackground(new java.awt.Color(248, 248, 248));
        btnHeader4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnHeader4.setText("<html>TIPOS DE <br> MANTENIMIENTO </html>");
        btnHeader4.setBorder(null);
        btnHeader4.setBorderPainted(false);
        btnHeader4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader.add(btnHeader4, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 0, 196, 70));

        add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        pnlMain.setPreferredSize(new java.awt.Dimension(684, 694));
        pnlMain.setLayout(new java.awt.CardLayout());

        pnlMain1.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain1.setMinimumSize(new java.awt.Dimension(684, 685));
        pnlMain1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkEstado4.setText("EN MANTENIMIENTO");
        pnlMain1.add(checkEstado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        btnModificarSede3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnModificarSede3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTableEdit.png"))); // NOI18N
        btnModificarSede3.setText("MODIFICAR");
        btnModificarSede3.setToolTipText("");
        btnModificarSede3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarSede3.setIconTextGap(10);
        btnModificarSede3.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnModificarSede3.setMaximumSize(new java.awt.Dimension(125, 35));
        btnModificarSede3.setMinimumSize(new java.awt.Dimension(125, 35));
        btnModificarSede3.setPreferredSize(new java.awt.Dimension(125, 35));
        pnlMain1.add(btnModificarSede3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 160, 40));

        btnDeleteFromTable1.setBackground(new java.awt.Color(102, 0, 0));
        btnDeleteFromTable1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDeleteFromTable1.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFromTable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ligth/iconTrash.png"))); // NOI18N
        btnDeleteFromTable1.setText("ELIMINAR");
        btnDeleteFromTable1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDeleteFromTable1.setIconTextGap(10);
        btnDeleteFromTable1.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain1.add(btnDeleteFromTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 600, 160, 40));

        btnFormModifyTransportista1.setBackground(new java.awt.Color(153, 255, 153));
        btnFormModifyTransportista1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnFormModifyTransportista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnFormModifyTransportista1.setText("<html>REGISTAR<br>UNIDAD</html>");
        btnFormModifyTransportista1.setToolTipText("");
        btnFormModifyTransportista1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFormModifyTransportista1.setIconTextGap(10);
        btnFormModifyTransportista1.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain1.add(btnFormModifyTransportista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 160, 60));

        txtFilterSede3.setBackground(new java.awt.Color(242, 242, 242));
        txtFilterSede3.setBorder(null);
        txtFilterSede3.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtFilterSede3.setOpaque(true);
        pnlMain1.add(txtFilterSede3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 40));

        btnSearch4.setBackground(new java.awt.Color(242, 242, 242));
        btnSearch4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearch4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearch4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch4.setOpaque(true);
        pnlMain1.add(btnSearch4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 40, 40));

        tblSedes2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tblSedes2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        tblSedes2.setRowHeight(35);
        jScrollPane4.setViewportView(tblSedes2);

        pnlMain1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 980, 480));

        checkEstado9.setText("NO DISPONIBLE");
        pnlMain1.add(checkEstado9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        btnRecargar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconRefresh.png"))); // NOI18N
        btnRecargar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMain1.add(btnRecargar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 30, -1));

        pnlMain.add(pnlMain1, "card2");

        pnlMain2.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain2.setMinimumSize(new java.awt.Dimension(684, 685));
        pnlMain2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkEstado8.setText("NO DISPONIBLE");
        pnlMain2.add(checkEstado8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnModificarSede7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnModificarSede7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTableEdit.png"))); // NOI18N
        btnModificarSede7.setText("MODIFICAR");
        btnModificarSede7.setToolTipText("");
        btnModificarSede7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarSede7.setIconTextGap(10);
        btnModificarSede7.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnModificarSede7.setMaximumSize(new java.awt.Dimension(125, 35));
        btnModificarSede7.setMinimumSize(new java.awt.Dimension(125, 35));
        btnModificarSede7.setPreferredSize(new java.awt.Dimension(125, 35));
        pnlMain2.add(btnModificarSede7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 160, 40));

        btnDeleteFromTable5.setBackground(new java.awt.Color(102, 0, 0));
        btnDeleteFromTable5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDeleteFromTable5.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFromTable5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ligth/iconTrash.png"))); // NOI18N
        btnDeleteFromTable5.setText("ELIMINAR");
        btnDeleteFromTable5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDeleteFromTable5.setIconTextGap(10);
        btnDeleteFromTable5.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain2.add(btnDeleteFromTable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 610, 160, 40));

        btnFormModifyTransportista5.setBackground(new java.awt.Color(153, 255, 153));
        btnFormModifyTransportista5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnFormModifyTransportista5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnFormModifyTransportista5.setText("<html>REGISTAR<br>PROPIETARIO</html>");
        btnFormModifyTransportista5.setToolTipText("");
        btnFormModifyTransportista5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFormModifyTransportista5.setIconTextGap(10);
        btnFormModifyTransportista5.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain2.add(btnFormModifyTransportista5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 160, 60));

        txtFilterSede7.setBackground(new java.awt.Color(242, 242, 242));
        txtFilterSede7.setBorder(null);
        txtFilterSede7.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtFilterSede7.setOpaque(true);
        pnlMain2.add(txtFilterSede7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 40));

        btnSearch8.setBackground(new java.awt.Color(242, 242, 242));
        btnSearch8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearch8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearch8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch8.setOpaque(true);
        pnlMain2.add(btnSearch8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 40, 40));

        tblSedes6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tblSedes6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSedes6.setRowHeight(35);
        jScrollPane8.setViewportView(tblSedes6);

        pnlMain2.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 980, 490));

        btnRecargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconRefresh.png"))); // NOI18N
        btnRecargar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMain2.add(btnRecargar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 30, -1, -1));

        pnlMain.add(pnlMain2, "card2");

        add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1000, 660));
    }// </editor-fold>//GEN-END:initComponents
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDeleteFromTable1;
    public javax.swing.JButton btnDeleteFromTable5;
    public javax.swing.JButton btnFormModifyTransportista1;
    public javax.swing.JButton btnFormModifyTransportista5;
    public javax.swing.JToggleButton btnHeader1;
    public javax.swing.JToggleButton btnHeader2;
    public javax.swing.JToggleButton btnHeader3;
    public javax.swing.JToggleButton btnHeader4;
    public javax.swing.JButton btnModificarSede3;
    public javax.swing.JButton btnModificarSede7;
    public javax.swing.JButton btnRecargar;
    public javax.swing.JButton btnRecargar1;
    private javax.swing.JLabel btnSearch4;
    private javax.swing.JLabel btnSearch8;
    public javax.swing.JCheckBox checkEstado4;
    public javax.swing.JCheckBox checkEstado8;
    public javax.swing.JCheckBox checkEstado9;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    public javax.swing.JPanel pnlMain1;
    public javax.swing.JPanel pnlMain2;
    public javax.swing.JTable tblSedes2;
    public javax.swing.JTable tblSedes6;
    public javax.swing.JTextField txtFilterSede3;
    public javax.swing.JTextField txtFilterSede7;
    // End of variables declaration//GEN-END:variables
}
