/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TRANSPORTE.VISTAS.RUTAS;

/**
 *
 * @author arnal
 */
public class mainRutas extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */

    public mainRutas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        btnHeader1 = new javax.swing.JToggleButton();
        pnlMain = new javax.swing.JPanel();
        pnlMain1 = new javax.swing.JPanel();
        btnModificarSede3 = new javax.swing.JButton();
        btnDeleteFromTable1 = new javax.swing.JButton();
        btnFormModifyTransportista1 = new javax.swing.JButton();
        txtFilterSede3 = new javax.swing.JTextField();
        btnSearch4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSedes2 = new javax.swing.JTable();
        btnRecargar1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(684, 694));
        setName("prestamos"); // NOI18N
        setPreferredSize(new java.awt.Dimension(684, 694));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHeader1.setBackground(new java.awt.Color(248, 248, 248));
        btnHeader1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnHeader1.setSelected(true);
        btnHeader1.setText("RUTAS");
        btnHeader1.setBorder(null);
        btnHeader1.setBorderPainted(false);
        btnHeader1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader.add(btnHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 196, 70));

        add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        pnlMain.setPreferredSize(new java.awt.Dimension(684, 694));
        pnlMain.setLayout(new java.awt.CardLayout());

        pnlMain1.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain1.setMinimumSize(new java.awt.Dimension(684, 685));
        pnlMain1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificarSede3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnModificarSede3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTableEdit.png"))); // NOI18N
        btnModificarSede3.setText("MODIFICAR");
        btnModificarSede3.setToolTipText("");
        btnModificarSede3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarSede3.setIconTextGap(10);
        btnModificarSede3.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnModificarSede3.setMaximumSize(new java.awt.Dimension(125, 35));
        btnModificarSede3.setMinimumSize(new java.awt.Dimension(125, 35));
        btnModificarSede3.setPreferredSize(new java.awt.Dimension(125, 35));
        pnlMain1.add(btnModificarSede3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 160, 40));

        btnDeleteFromTable1.setBackground(new java.awt.Color(102, 0, 0));
        btnDeleteFromTable1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDeleteFromTable1.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFromTable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ligth/iconTrash.png"))); // NOI18N
        btnDeleteFromTable1.setText("ELIMINAR");
        btnDeleteFromTable1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDeleteFromTable1.setIconTextGap(10);
        btnDeleteFromTable1.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain1.add(btnDeleteFromTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 600, 160, 40));

        btnFormModifyTransportista1.setBackground(new java.awt.Color(153, 255, 153));
        btnFormModifyTransportista1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnFormModifyTransportista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnFormModifyTransportista1.setText("<html>REGISTAR<br>RUTA</html>");
        btnFormModifyTransportista1.setToolTipText("");
        btnFormModifyTransportista1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFormModifyTransportista1.setIconTextGap(10);
        btnFormModifyTransportista1.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain1.add(btnFormModifyTransportista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 160, 60));

        txtFilterSede3.setBackground(new java.awt.Color(242, 242, 242));
        txtFilterSede3.setBorder(null);
        txtFilterSede3.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtFilterSede3.setOpaque(true);
        pnlMain1.add(txtFilterSede3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 40));

        btnSearch4.setBackground(new java.awt.Color(242, 242, 242));
        btnSearch4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearch4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearch4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch4.setOpaque(true);
        pnlMain1.add(btnSearch4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 40, 40));

        tblSedes2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tblSedes2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10"
            }
        ));
        tblSedes2.setRowHeight(35);
        jScrollPane4.setViewportView(tblSedes2);

        pnlMain1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 980, 480));

        btnRecargar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconRefresh.png"))); // NOI18N
        btnRecargar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnlMain1.add(btnRecargar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 30, -1));

        pnlMain.add(pnlMain1, "card2");

        add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1000, 660));
    }// </editor-fold>//GEN-END:initComponents
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDeleteFromTable1;
    public javax.swing.JButton btnFormModifyTransportista1;
    public javax.swing.JToggleButton btnHeader1;
    public javax.swing.JButton btnModificarSede3;
    public javax.swing.JButton btnRecargar1;
    private javax.swing.JLabel btnSearch4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    public javax.swing.JPanel pnlMain1;
    public javax.swing.JTable tblSedes2;
    public javax.swing.JTextField txtFilterSede3;
    // End of variables declaration//GEN-END:variables
}
