/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TRANSPORTE.VISTAS.GUIAS;

/**
 *
 * @author milag
 */
public class formViatico extends javax.swing.JPanel {

    /**
     * Creates new form formViatico
     */
    public formViatico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        subMain1 = new javax.swing.JPanel();
        btnModificarSede3 = new javax.swing.JButton();
        btnDeleteFromTable1 = new javax.swing.JButton();
        btnLoadForm = new javax.swing.JButton();
        txtFilterSede3 = new javax.swing.JTextField();
        btnSearch4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSedes2 = new javax.swing.JTable();
        lblTitlePersona = new javax.swing.JLabel();

        subMain1.setBackground(new java.awt.Color(255, 255, 255));
        subMain1.setMinimumSize(new java.awt.Dimension(684, 685));
        subMain1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnModificarSede3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnModificarSede3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTableEdit.png"))); // NOI18N
        btnModificarSede3.setText("MODIFICAR");
        btnModificarSede3.setToolTipText("");
        btnModificarSede3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarSede3.setIconTextGap(10);
        btnModificarSede3.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnModificarSede3.setMaximumSize(new java.awt.Dimension(125, 35));
        btnModificarSede3.setMinimumSize(new java.awt.Dimension(125, 35));
        btnModificarSede3.setPreferredSize(new java.awt.Dimension(125, 35));
        subMain1.add(btnModificarSede3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 160, 40));

        btnDeleteFromTable1.setBackground(new java.awt.Color(102, 0, 0));
        btnDeleteFromTable1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDeleteFromTable1.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFromTable1.setText("ELIMINAR");
        btnDeleteFromTable1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDeleteFromTable1.setIconTextGap(10);
        btnDeleteFromTable1.setMargin(new java.awt.Insets(2, 1, 3, 14));
        subMain1.add(btnDeleteFromTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 570, 160, 40));

        btnLoadForm.setBackground(new java.awt.Color(153, 255, 153));
        btnLoadForm.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnLoadForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnLoadForm.setText("<html>NUEVA<br>GUIA</html>");
        btnLoadForm.setToolTipText("");
        btnLoadForm.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLoadForm.setIconTextGap(10);
        btnLoadForm.setMargin(new java.awt.Insets(2, 1, 3, 14));
        subMain1.add(btnLoadForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 120, 160, 60));

        txtFilterSede3.setBackground(new java.awt.Color(242, 242, 242));
        txtFilterSede3.setBorder(null);
        txtFilterSede3.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtFilterSede3.setOpaque(true);
        subMain1.add(txtFilterSede3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 280, 40));

        btnSearch4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearch4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearch4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch4.setOpaque(true);
        subMain1.add(btnSearch4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 40, 40));

        tblSedes2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tblSedes2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSedes2.setRowHeight(35);
        jScrollPane4.setViewportView(tblSedes2);

        subMain1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 980, 410));

        lblTitlePersona.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitlePersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePersona.setText("NUEVA GUIA");
        subMain1.add(lblTitlePersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 980, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(subMain1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(subMain1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 749, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDeleteFromTable1;
    public javax.swing.JButton btnLoadForm;
    public javax.swing.JButton btnModificarSede3;
    private javax.swing.JLabel btnSearch4;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JLabel lblTitlePersona;
    public javax.swing.JPanel subMain1;
    public javax.swing.JTable tblSedes2;
    public javax.swing.JTextField txtFilterSede3;
    // End of variables declaration//GEN-END:variables
}
