/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TRANSPORTE.VISTAS.GUIAS;

/**
 *
 * @author milag
 */
public class formReciboEntrega extends javax.swing.JPanel {

    /**
     * Creates new form formReciboEntrega
     */
    public formReciboEntrega() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUser3 = new javax.swing.JPanel();
        lblClienteFacturaReciboEntrega = new javax.swing.JLabel();
        txtClienteReciboEntrega = new javax.swing.JTextField();
        lblCodigoGuiaReciboEntrega = new javax.swing.JLabel();
        txtCodigoGuiaReciboEntrega = new javax.swing.JTextField();
        txtDescripcionFacturaGuiaReciboEntrega = new javax.swing.JTextField();
        lblDescripGuiaReciboEntrega = new javax.swing.JLabel();
        lblInfoFactura = new javax.swing.JLabel();
        btnCancelFormFactura = new javax.swing.JButton();
        btnCleanFormFactura = new javax.swing.JButton();
        btnSetFormImprimir = new javax.swing.JButton();
        lblTitleReciboEntrega = new javax.swing.JLabel();
        btnSearchCodigoGuiaReciboEntrega = new javax.swing.JLabel();
        lblMontoServicio1 = new javax.swing.JLabel();
        txtCodigoReciboEntrega = new javax.swing.JTextField();
        lblMontoReciboEntrega = new javax.swing.JLabel();
        txtMontoReciboEntrega = new javax.swing.JTextField();
        lblFirmaRecibido = new javax.swing.JLabel();
        lblIFirmaDeRecibido = new javax.swing.JLabel();

        pnlUser3.setBackground(new java.awt.Color(255, 255, 255));

        lblClienteFacturaReciboEntrega.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblClienteFacturaReciboEntrega.setText("CLIENTE");

        txtClienteReciboEntrega.setBackground(new java.awt.Color(250, 250, 250));
        txtClienteReciboEntrega.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtClienteReciboEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtClienteReciboEntrega.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtClienteReciboEntrega.setOpaque(true);

        lblCodigoGuiaReciboEntrega.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCodigoGuiaReciboEntrega.setText("COD. GUIA");

        txtCodigoGuiaReciboEntrega.setBackground(new java.awt.Color(250, 250, 250));
        txtCodigoGuiaReciboEntrega.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtCodigoGuiaReciboEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCodigoGuiaReciboEntrega.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigoGuiaReciboEntrega.setOpaque(true);

        txtDescripcionFacturaGuiaReciboEntrega.setBackground(new java.awt.Color(250, 250, 250));
        txtDescripcionFacturaGuiaReciboEntrega.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtDescripcionFacturaGuiaReciboEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescripcionFacturaGuiaReciboEntrega.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDescripcionFacturaGuiaReciboEntrega.setOpaque(true);

        lblDescripGuiaReciboEntrega.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblDescripGuiaReciboEntrega.setText("DESCRIPCION");

        lblInfoFactura.setForeground(new java.awt.Color(255, 0, 51));
        lblInfoFactura.setText("* ");

        btnCancelFormFactura.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelFormFactura.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelFormFactura.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelFormFactura.setText("CANCELAR");
        btnCancelFormFactura.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelFormFactura.setIconTextGap(10);
        btnCancelFormFactura.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCancelFormFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelFormFacturaActionPerformed(evt);
            }
        });

        btnCleanFormFactura.setBackground(new java.awt.Color(230, 230, 230));
        btnCleanFormFactura.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCleanFormFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMop.png"))); // NOI18N
        btnCleanFormFactura.setText("LIMPIAR");
        btnCleanFormFactura.setToolTipText("");
        btnCleanFormFactura.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCleanFormFactura.setIconTextGap(10);
        btnCleanFormFactura.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCleanFormFactura.setMaximumSize(new java.awt.Dimension(125, 35));
        btnCleanFormFactura.setMinimumSize(new java.awt.Dimension(125, 35));
        btnCleanFormFactura.setPreferredSize(new java.awt.Dimension(125, 35));

        btnSetFormImprimir.setBackground(new java.awt.Color(153, 255, 153));
        btnSetFormImprimir.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSetFormImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnSetFormImprimir.setText("IMPRIMIR");
        btnSetFormImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSetFormImprimir.setIconTextGap(10);
        btnSetFormImprimir.setMargin(new java.awt.Insets(0, 0, 0, 0));

        lblTitleReciboEntrega.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitleReciboEntrega.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleReciboEntrega.setText("RECIBO DE ENTREGA");

        btnSearchCodigoGuiaReciboEntrega.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearchCodigoGuiaReciboEntrega.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearchCodigoGuiaReciboEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchCodigoGuiaReciboEntrega.setOpaque(true);

        lblMontoServicio1.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        lblMontoServicio1.setText("Codigo de entrega");

        txtCodigoReciboEntrega.setBackground(new java.awt.Color(250, 250, 250));
        txtCodigoReciboEntrega.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtCodigoReciboEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCodigoReciboEntrega.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigoReciboEntrega.setOpaque(true);

        lblMontoReciboEntrega.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblMontoReciboEntrega.setText("MONTO");

        txtMontoReciboEntrega.setBackground(new java.awt.Color(250, 250, 250));
        txtMontoReciboEntrega.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtMontoReciboEntrega.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMontoReciboEntrega.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMontoReciboEntrega.setOpaque(true);

        lblFirmaRecibido.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        lblFirmaRecibido.setText("Firma de recibido");

        lblIFirmaDeRecibido.setForeground(new java.awt.Color(255, 0, 51));
        lblIFirmaDeRecibido.setText("* ");

        javax.swing.GroupLayout pnlUser3Layout = new javax.swing.GroupLayout(pnlUser3);
        pnlUser3.setLayout(pnlUser3Layout);
        pnlUser3Layout.setHorizontalGroup(
            pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUser3Layout.createSequentialGroup()
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblInfoFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMontoServicio1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoReciboEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripGuiaReciboEntrega)
                            .addGroup(pnlUser3Layout.createSequentialGroup()
                                .addComponent(lblCodigoGuiaReciboEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearchCodigoGuiaReciboEntrega))
                            .addComponent(lblClienteFacturaReciboEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMontoReciboEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCodigoGuiaReciboEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(txtClienteReciboEntrega)
                                .addComponent(txtMontoReciboEntrega))
                            .addComponent(txtDescripcionFacturaGuiaReciboEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitleReciboEntrega, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser3Layout.createSequentialGroup()
                        .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlUser3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblFirmaRecibido))
                            .addGroup(pnlUser3Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btnCancelFormFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                .addComponent(btnCleanFormFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUser3Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(btnSetFormImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlUser3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblIFirmaDeRecibido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(26, 26, 26)))
                .addContainerGap())
        );
        pnlUser3Layout.setVerticalGroup(
            pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitleReciboEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMontoServicio1)
                        .addComponent(txtCodigoReciboEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchCodigoGuiaReciboEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigoGuiaReciboEntrega)
                        .addComponent(txtCodigoGuiaReciboEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDescripGuiaReciboEntrega)
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtDescripcionFacturaGuiaReciboEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtClienteReciboEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblClienteFacturaReciboEntrega)))
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMontoReciboEntrega)
                            .addComponent(txtMontoReciboEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirmaRecibido)
                    .addComponent(lblIFirmaDeRecibido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelFormFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCleanFormFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetFormImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelFormFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelFormFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelFormFacturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelFormFactura;
    public javax.swing.JButton btnCleanFormFactura;
    private javax.swing.JLabel btnSearchCodigoGuiaReciboEntrega;
    public javax.swing.JButton btnSetFormImprimir;
    public javax.swing.JLabel lblClienteFacturaReciboEntrega;
    public javax.swing.JLabel lblCodigoGuiaReciboEntrega;
    public javax.swing.JLabel lblDescripGuiaReciboEntrega;
    public javax.swing.JLabel lblFirmaRecibido;
    public javax.swing.JLabel lblIFirmaDeRecibido;
    public javax.swing.JLabel lblInfoFactura;
    public javax.swing.JLabel lblMontoReciboEntrega;
    public javax.swing.JLabel lblMontoServicio1;
    public javax.swing.JLabel lblTitleReciboEntrega;
    public javax.swing.JPanel pnlUser3;
    public javax.swing.JTextField txtClienteReciboEntrega;
    public javax.swing.JTextField txtCodigoGuiaReciboEntrega;
    public javax.swing.JTextField txtCodigoReciboEntrega;
    public javax.swing.JTextField txtDescripcionFacturaGuiaReciboEntrega;
    public javax.swing.JTextField txtMontoReciboEntrega;
    // End of variables declaration//GEN-END:variables
}
