/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TRANSPORTE.VISTAS.GUIAS;

/**
 *
 * @author milag
 */
public class formGestionViatico extends javax.swing.JPanel {

    /**
     * Creates new form formGestionViatico
     */
    public formGestionViatico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormPersona = new javax.swing.JPanel();
        pnlUser1 = new javax.swing.JPanel();
        lblTitlePersona = new javax.swing.JLabel();
        lblEstatusViatico = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblCedula3 = new javax.swing.JLabel();
        txtCodiogoGuia = new javax.swing.JTextField();
        txtMontoViatico = new javax.swing.JTextField();
        lblCategoria1 = new javax.swing.JLabel();
        lblInfoPersona = new javax.swing.JLabel();
        lblControlFormPersona = new javax.swing.JLabel();
        jcbxTipoGastoOperativo = new javax.swing.JComboBox<>();
        lblCategoria3 = new javax.swing.JLabel();
        jcbxEstadoGuia = new javax.swing.JComboBox<>();
        btnSearchMecanico = new javax.swing.JLabel();
        btnCancelFormViatico = new javax.swing.JButton();
        btnCleanFormViatico = new javax.swing.JButton();
        btnSetFormViatico = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblFormViatico = new javax.swing.JTable();

        pnlFormPersona.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormPersona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUser1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitlePersona.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitlePersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePersona.setText("GESTION DE VIATICOS");

        lblEstatusViatico.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblEstatusViatico.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstatusViatico.setText("0");
        lblEstatusViatico.setEnabled(false);

        lblNombre1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblNombre1.setText("GUIA");

        lblCedula3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCedula3.setText("GASTO OPERATIVO");

        txtCodiogoGuia.setBackground(new java.awt.Color(250, 250, 250));
        txtCodiogoGuia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtCodiogoGuia.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCodiogoGuia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodiogoGuia.setOpaque(true);

        txtMontoViatico.setBackground(new java.awt.Color(250, 250, 250));
        txtMontoViatico.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtMontoViatico.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMontoViatico.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMontoViatico.setOpaque(true);

        lblCategoria1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria1.setText("MONTO PRESUPUESTO");

        lblInfoPersona.setForeground(new java.awt.Color(255, 0, 51));
        lblInfoPersona.setText("* ");

        lblControlFormPersona.setText("1");

        jcbxTipoGastoOperativo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E", "J", "G" }));
        jcbxTipoGastoOperativo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblCategoria3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria3.setText("ESTADO");

        jcbxEstadoGuia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO DISPONIBLE", "DISPONIBLE" }));
        jcbxEstadoGuia.setSelectedIndex(1);
        jcbxEstadoGuia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jcbxEstadoGuia.setEnabled(false);

        btnSearchMecanico.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearchMecanico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearchMecanico.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchMecanico.setOpaque(true);

        javax.swing.GroupLayout pnlUser1Layout = new javax.swing.GroupLayout(pnlUser1);
        pnlUser1.setLayout(pnlUser1Layout);
        pnlUser1Layout.setHorizontalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUser1Layout.createSequentialGroup()
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(lblControlFormPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblTitlePersona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                                        .addComponent(btnSearchMecanico)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(pnlUser1Layout.createSequentialGroup()
                                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                                .addComponent(lblCategoria1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtMontoViatico, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(59, 59, 59))
                                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                                .addComponent(lblCedula3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jcbxTipoGastoOperativo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(24, 24, 24)
                                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(32, 32, 32)))
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jcbxEstadoGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodiogoGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lblInfoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblEstatusViatico, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUser1Layout.setVerticalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                .addComponent(lblControlFormPersona)
                .addGap(3, 3, 3)
                .addComponent(lblTitlePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstatusViatico, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblInfoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCodiogoGuia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchMecanico, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCedula3)
                        .addComponent(lblNombre1)
                        .addComponent(jcbxTipoGastoOperativo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoViatico, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria1)
                    .addComponent(jcbxEstadoGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCategoria3))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        pnlFormPersona.add(pnlUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 250));

        btnCancelFormViatico.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelFormViatico.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelFormViatico.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelFormViatico.setText("CANCELAR");
        btnCancelFormViatico.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelFormViatico.setIconTextGap(10);
        btnCancelFormViatico.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlFormPersona.add(btnCancelFormViatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 160, 40));

        btnCleanFormViatico.setBackground(new java.awt.Color(230, 230, 230));
        btnCleanFormViatico.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCleanFormViatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMop.png"))); // NOI18N
        btnCleanFormViatico.setText("LIMPIAR");
        btnCleanFormViatico.setToolTipText("");
        btnCleanFormViatico.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCleanFormViatico.setIconTextGap(10);
        btnCleanFormViatico.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCleanFormViatico.setMaximumSize(new java.awt.Dimension(125, 35));
        btnCleanFormViatico.setMinimumSize(new java.awt.Dimension(125, 35));
        btnCleanFormViatico.setPreferredSize(new java.awt.Dimension(125, 35));
        pnlFormPersona.add(btnCleanFormViatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 630, 160, 40));

        btnSetFormViatico.setBackground(new java.awt.Color(153, 255, 153));
        btnSetFormViatico.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSetFormViatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnSetFormViatico.setText("REGISTRAR");
        btnSetFormViatico.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSetFormViatico.setIconTextGap(10);
        btnSetFormViatico.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pnlFormPersona.add(btnSetFormViatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 630, 190, 40));

        tblFormViatico.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        tblFormViatico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFormViatico.setRowHeight(40);
        tblFormViatico.setRowMargin(10);
        jScrollPane4.setViewportView(tblFormViatico);

        pnlFormPersona.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 750, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelFormViatico;
    public javax.swing.JButton btnCleanFormViatico;
    private javax.swing.JLabel btnSearchMecanico;
    public javax.swing.JButton btnSetFormViatico;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JComboBox<String> jcbxEstadoGuia;
    public javax.swing.JComboBox<String> jcbxTipoGastoOperativo;
    public javax.swing.JLabel lblCategoria1;
    public javax.swing.JLabel lblCategoria3;
    public javax.swing.JLabel lblCedula3;
    public javax.swing.JLabel lblControlFormPersona;
    public javax.swing.JLabel lblEstatusViatico;
    public javax.swing.JLabel lblInfoPersona;
    public javax.swing.JLabel lblNombre1;
    public javax.swing.JLabel lblTitlePersona;
    private javax.swing.JPanel pnlFormPersona;
    public javax.swing.JPanel pnlUser1;
    public javax.swing.JTable tblFormViatico;
    public javax.swing.JTextField txtCodiogoGuia;
    public javax.swing.JTextField txtMontoViatico;
    // End of variables declaration//GEN-END:variables
}
