/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TRANSPORTE.VISTAS.GUIAS;

/**
 *
 * @author milag
 */
public class formFactura extends javax.swing.JPanel {

    /**
     * Creates new form formFactura
     */
    public formFactura() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUser3 = new javax.swing.JPanel();
        lblClienteFactura = new javax.swing.JLabel();
        txtClienteFactura = new javax.swing.JTextField();
        lblCodigoGuia = new javax.swing.JLabel();
        txtCodigoGuia = new javax.swing.JTextField();
        txtDescripcionFacturaGuia = new javax.swing.JTextField();
        lblDescripGuia = new javax.swing.JLabel();
        lblInfoFactura = new javax.swing.JLabel();
        btnCancelFormFactura = new javax.swing.JButton();
        btnCleanFormFactura = new javax.swing.JButton();
        btnSetFormImprimir = new javax.swing.JButton();
        lblTitleFactura = new javax.swing.JLabel();
        btnSearchCodigoGuia = new javax.swing.JLabel();
        lblMontoServicio1 = new javax.swing.JLabel();
        txtCodigoFactura = new javax.swing.JTextField();
        lblMontoFactura = new javax.swing.JLabel();
        txtMontoFactura = new javax.swing.JTextField();

        pnlUser3.setBackground(new java.awt.Color(255, 255, 255));

        lblClienteFactura.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblClienteFactura.setText("CLIENTE");

        txtClienteFactura.setBackground(new java.awt.Color(250, 250, 250));
        txtClienteFactura.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtClienteFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtClienteFactura.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtClienteFactura.setOpaque(true);

        lblCodigoGuia.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCodigoGuia.setText("COD. GUIA");

        txtCodigoGuia.setBackground(new java.awt.Color(250, 250, 250));
        txtCodigoGuia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtCodigoGuia.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCodigoGuia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigoGuia.setOpaque(true);

        txtDescripcionFacturaGuia.setBackground(new java.awt.Color(250, 250, 250));
        txtDescripcionFacturaGuia.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtDescripcionFacturaGuia.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescripcionFacturaGuia.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDescripcionFacturaGuia.setOpaque(true);

        lblDescripGuia.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblDescripGuia.setText("DESCRIPCION");

        lblInfoFactura.setForeground(new java.awt.Color(255, 0, 51));
        lblInfoFactura.setText("* ");

        btnCancelFormFactura.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelFormFactura.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelFormFactura.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelFormFactura.setText("CANCELAR");
        btnCancelFormFactura.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelFormFactura.setIconTextGap(10);
        btnCancelFormFactura.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCancelFormFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelFormFacturaActionPerformed(evt);
            }
        });

        btnCleanFormFactura.setBackground(new java.awt.Color(230, 230, 230));
        btnCleanFormFactura.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCleanFormFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMop.png"))); // NOI18N
        btnCleanFormFactura.setText("LIMPIAR");
        btnCleanFormFactura.setToolTipText("");
        btnCleanFormFactura.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCleanFormFactura.setIconTextGap(10);
        btnCleanFormFactura.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCleanFormFactura.setMaximumSize(new java.awt.Dimension(125, 35));
        btnCleanFormFactura.setMinimumSize(new java.awt.Dimension(125, 35));
        btnCleanFormFactura.setPreferredSize(new java.awt.Dimension(125, 35));

        btnSetFormImprimir.setBackground(new java.awt.Color(153, 255, 153));
        btnSetFormImprimir.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSetFormImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnSetFormImprimir.setText("IMPRIMIR");
        btnSetFormImprimir.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSetFormImprimir.setIconTextGap(10);
        btnSetFormImprimir.setMargin(new java.awt.Insets(0, 0, 0, 0));

        lblTitleFactura.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitleFactura.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleFactura.setText("FACTURA");

        btnSearchCodigoGuia.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearchCodigoGuia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearchCodigoGuia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchCodigoGuia.setOpaque(true);

        lblMontoServicio1.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        lblMontoServicio1.setText("Codigo de factura");

        txtCodigoFactura.setBackground(new java.awt.Color(250, 250, 250));
        txtCodigoFactura.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtCodigoFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCodigoFactura.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigoFactura.setOpaque(true);

        lblMontoFactura.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblMontoFactura.setText("Monto");

        txtMontoFactura.setBackground(new java.awt.Color(250, 250, 250));
        txtMontoFactura.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtMontoFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMontoFactura.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMontoFactura.setOpaque(true);

        javax.swing.GroupLayout pnlUser3Layout = new javax.swing.GroupLayout(pnlUser3);
        pnlUser3.setLayout(pnlUser3Layout);
        pnlUser3Layout.setHorizontalGroup(
            pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUser3Layout.createSequentialGroup()
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblInfoFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(75, 75, 75)
                        .addComponent(lblMontoServicio1)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDescripGuia)
                            .addGroup(pnlUser3Layout.createSequentialGroup()
                                .addComponent(lblCodigoGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSearchCodigoGuia))
                            .addComponent(lblClienteFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMontoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDescripcionFacturaGuia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(txtCodigoGuia)
                            .addComponent(txtClienteFactura)
                            .addComponent(txtMontoFactura))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblTitleFactura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnCancelFormFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(btnCleanFormFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnSetFormImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUser3Layout.setVerticalGroup(
            pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblTitleFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMontoServicio1)
                        .addComponent(txtCodigoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchCodigoGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigoGuia)
                        .addComponent(txtCodigoGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcionFacturaGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripGuia))
                .addGap(36, 36, 36)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClienteFactura)
                    .addComponent(txtClienteFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblMontoFactura))
                    .addGroup(pnlUser3Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(txtMontoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(pnlUser3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelFormFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCleanFormFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetFormImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelFormFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelFormFacturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelFormFacturaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelFormFactura;
    public javax.swing.JButton btnCleanFormFactura;
    private javax.swing.JLabel btnSearchCodigoGuia;
    public javax.swing.JButton btnSetFormImprimir;
    public javax.swing.JLabel lblClienteFactura;
    public javax.swing.JLabel lblCodigoGuia;
    public javax.swing.JLabel lblDescripGuia;
    public javax.swing.JLabel lblInfoFactura;
    public javax.swing.JLabel lblMontoFactura;
    public javax.swing.JLabel lblMontoServicio1;
    public javax.swing.JLabel lblTitleFactura;
    public javax.swing.JPanel pnlUser3;
    public javax.swing.JTextField txtClienteFactura;
    public javax.swing.JTextField txtCodigoFactura;
    public javax.swing.JTextField txtCodigoGuia;
    public javax.swing.JTextField txtDescripcionFacturaGuia;
    public javax.swing.JTextField txtMontoFactura;
    // End of variables declaration//GEN-END:variables
}
