/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TRANSPORTE.VISTAS.GUIAS;

/**
 *
 * @author milag
 */
public class formServicios extends javax.swing.JPanel {

    /**
     * Creates new form formServicios
     */
    public formServicios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlUser1 = new javax.swing.JPanel();
        lblNombreServicio = new javax.swing.JLabel();
        txtNombreTipoServicio = new javax.swing.JTextField();
        lblCodigoTipoServicio = new javax.swing.JLabel();
        txtCodigoTipoServicio = new javax.swing.JTextField();
        txtDescripcionTIpoServicio = new javax.swing.JTextField();
        lblDescripServicio = new javax.swing.JLabel();
        lblInfoTipoServicio = new javax.swing.JLabel();
        btnCancelFormTipoServicio = new javax.swing.JButton();
        btnCleanFormTipoServicio = new javax.swing.JButton();
        btnSetFormTipoMante = new javax.swing.JButton();
        lblTitleMantemimiento = new javax.swing.JLabel();
        btnEliminarFormServicio = new javax.swing.JButton();
        btnSearchTipoServicio = new javax.swing.JLabel();
        lblMontoServicio1 = new javax.swing.JLabel();
        txtMontoTipoServicio = new javax.swing.JTextField();

        pnlUser1.setBackground(new java.awt.Color(255, 255, 255));

        lblNombreServicio.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblNombreServicio.setText("NOMBRE");

        txtNombreTipoServicio.setBackground(new java.awt.Color(250, 250, 250));
        txtNombreTipoServicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtNombreTipoServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombreTipoServicio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombreTipoServicio.setOpaque(true);

        lblCodigoTipoServicio.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCodigoTipoServicio.setText("CODIGO");

        txtCodigoTipoServicio.setBackground(new java.awt.Color(250, 250, 250));
        txtCodigoTipoServicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtCodigoTipoServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCodigoTipoServicio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCodigoTipoServicio.setOpaque(true);

        txtDescripcionTIpoServicio.setBackground(new java.awt.Color(250, 250, 250));
        txtDescripcionTIpoServicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtDescripcionTIpoServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDescripcionTIpoServicio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDescripcionTIpoServicio.setOpaque(true);

        lblDescripServicio.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblDescripServicio.setText("DESCRIPCION");

        lblInfoTipoServicio.setForeground(new java.awt.Color(255, 0, 51));
        lblInfoTipoServicio.setText("* ");

        btnCancelFormTipoServicio.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelFormTipoServicio.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelFormTipoServicio.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelFormTipoServicio.setText("CANCELAR");
        btnCancelFormTipoServicio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelFormTipoServicio.setIconTextGap(10);
        btnCancelFormTipoServicio.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCancelFormTipoServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelFormTipoServicioActionPerformed(evt);
            }
        });

        btnCleanFormTipoServicio.setBackground(new java.awt.Color(230, 230, 230));
        btnCleanFormTipoServicio.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCleanFormTipoServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMop.png"))); // NOI18N
        btnCleanFormTipoServicio.setText("LIMPIAR");
        btnCleanFormTipoServicio.setToolTipText("");
        btnCleanFormTipoServicio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCleanFormTipoServicio.setIconTextGap(10);
        btnCleanFormTipoServicio.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCleanFormTipoServicio.setMaximumSize(new java.awt.Dimension(125, 35));
        btnCleanFormTipoServicio.setMinimumSize(new java.awt.Dimension(125, 35));
        btnCleanFormTipoServicio.setPreferredSize(new java.awt.Dimension(125, 35));

        btnSetFormTipoMante.setBackground(new java.awt.Color(153, 255, 153));
        btnSetFormTipoMante.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSetFormTipoMante.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnSetFormTipoMante.setText("REGISTRAR");
        btnSetFormTipoMante.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSetFormTipoMante.setIconTextGap(10);
        btnSetFormTipoMante.setMargin(new java.awt.Insets(0, 0, 0, 0));

        lblTitleMantemimiento.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitleMantemimiento.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitleMantemimiento.setText("TIPO DE SERVICIOS");

        btnEliminarFormServicio.setBackground(new java.awt.Color(102, 0, 0));
        btnEliminarFormServicio.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnEliminarFormServicio.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarFormServicio.setText("ELIMINAR");
        btnEliminarFormServicio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnEliminarFormServicio.setIconTextGap(10);
        btnEliminarFormServicio.setMargin(new java.awt.Insets(2, 1, 3, 14));

        btnSearchTipoServicio.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearchTipoServicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearchTipoServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearchTipoServicio.setOpaque(true);

        lblMontoServicio1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblMontoServicio1.setText("MONTO");

        txtMontoTipoServicio.setBackground(new java.awt.Color(250, 250, 250));
        txtMontoTipoServicio.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtMontoTipoServicio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtMontoTipoServicio.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtMontoTipoServicio.setOpaque(true);

        javax.swing.GroupLayout pnlUser1Layout = new javax.swing.GroupLayout(pnlUser1);
        pnlUser1.setLayout(pnlUser1Layout);
        pnlUser1Layout.setHorizontalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUser1Layout.createSequentialGroup()
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInfoTipoServicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblDescripServicio)
                                .addGroup(pnlUser1Layout.createSequentialGroup()
                                    .addComponent(lblCodigoTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSearchTipoServicio)))
                            .addComponent(btnCancelFormTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtDescripcionTIpoServicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                    .addComponent(txtCodigoTipoServicio))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                                .addComponent(btnCleanFormTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(43, 43, 43)))
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                .addComponent(lblNombreServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(txtNombreTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(btnEliminarFormServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(btnSetFormTipoMante, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                .addComponent(lblMontoServicio1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtMontoTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 21, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pnlUser1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTitleMantemimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUser1Layout.setVerticalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitleMantemimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblInfoTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearchTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCodigoTipoServicio)
                        .addComponent(txtCodigoTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblNombreServicio)
                        .addComponent(txtNombreTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDescripcionTIpoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDescripServicio)
                    .addComponent(lblMontoServicio1)
                    .addComponent(txtMontoTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelFormTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCleanFormTipoServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarFormServicio, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSetFormTipoMante, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlUser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelFormTipoServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelFormTipoServicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelFormTipoServicioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelFormTipoServicio;
    public javax.swing.JButton btnCleanFormTipoServicio;
    public javax.swing.JButton btnEliminarFormServicio;
    private javax.swing.JLabel btnSearchTipoServicio;
    public javax.swing.JButton btnSetFormTipoMante;
    public javax.swing.JLabel lblCodigoTipoServicio;
    public javax.swing.JLabel lblDescripServicio;
    public javax.swing.JLabel lblInfoTipoServicio;
    public javax.swing.JLabel lblMontoServicio1;
    public javax.swing.JLabel lblNombreServicio;
    public javax.swing.JLabel lblTitleMantemimiento;
    public javax.swing.JPanel pnlUser1;
    public javax.swing.JTextField txtCodigoTipoServicio;
    public javax.swing.JTextField txtDescripcionTIpoServicio;
    public javax.swing.JTextField txtMontoTipoServicio;
    public javax.swing.JTextField txtNombreTipoServicio;
    // End of variables declaration//GEN-END:variables
}
