/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TRANSPORTE.VISTAS.GUIAS;

import TRANSPORTE.VISTAS.UNIDADES.*;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 *
 * @author arnal
 */
public class mainGuias extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */

    public mainGuias() {
        initComponents();
        btnHeader2.setVisible(false);
        btnHeader3.setVisible(false);
        btnHeader4.setVisible(false);
        subHeader1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        btnHeader1 = new javax.swing.JToggleButton();
        btnHeader2 = new javax.swing.JToggleButton();
        btnHeader3 = new javax.swing.JToggleButton();
        btnHeader4 = new javax.swing.JToggleButton();
        pnlMain = new javax.swing.JPanel();
        pnlMain1 = new javax.swing.JPanel();
        subMain1 = new javax.swing.JPanel();
        checkEstado4 = new javax.swing.JCheckBox();
        btnModificarSede3 = new javax.swing.JButton();
        btnDeleteFromTable1 = new javax.swing.JButton();
        btnLoadForm = new javax.swing.JButton();
        txtFilterSede3 = new javax.swing.JTextField();
        btnSearch4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSedes2 = new javax.swing.JTable();
        subHeader1 = new javax.swing.JPanel();
        btnHeader6 = new javax.swing.JToggleButton();
        btnHeader7 = new javax.swing.JToggleButton();
        pnlMain2 = new javax.swing.JPanel();
        checkEstado8 = new javax.swing.JCheckBox();
        btnModificarSede7 = new javax.swing.JButton();
        btnDeleteFromTable5 = new javax.swing.JButton();
        btnFormModifyTransportista5 = new javax.swing.JButton();
        txtFilterSede7 = new javax.swing.JTextField();
        btnSearch8 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        tblSedes6 = new javax.swing.JTable();
        pnlMain3 = new javax.swing.JPanel();
        checkEstado5 = new javax.swing.JCheckBox();
        btnModificarSede4 = new javax.swing.JButton();
        btnDeleteFromTable2 = new javax.swing.JButton();
        btnFormModifyTransportista2 = new javax.swing.JButton();
        txtFilterSede4 = new javax.swing.JTextField();
        btnSearch5 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblSedes3 = new javax.swing.JTable();
        pnlMain4 = new javax.swing.JPanel();
        checkEstado6 = new javax.swing.JCheckBox();
        btnModificarSede5 = new javax.swing.JButton();
        btnDeleteFromTable3 = new javax.swing.JButton();
        btnFormModifyTransportista3 = new javax.swing.JButton();
        txtFilterSede5 = new javax.swing.JTextField();
        btnSearch6 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblSedes4 = new javax.swing.JTable();
        pnlMain5 = new javax.swing.JPanel();
        checkEstado7 = new javax.swing.JCheckBox();
        btnModificarSede6 = new javax.swing.JButton();
        btnDeleteFromTable4 = new javax.swing.JButton();
        btnFormModifyTransportista4 = new javax.swing.JButton();
        txtFilterSede6 = new javax.swing.JTextField();
        btnSearch7 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblSedes5 = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(684, 694));
        setName("prestamos"); // NOI18N
        setPreferredSize(new java.awt.Dimension(684, 694));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHeader1.setBackground(new java.awt.Color(248, 248, 248));
        btnHeader1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnHeader1.setSelected(true);
        btnHeader1.setText("GUIAS");
        btnHeader1.setBorder(null);
        btnHeader1.setBorderPainted(false);
        btnHeader1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader.add(btnHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 196, 70));

        btnHeader2.setBackground(new java.awt.Color(248, 248, 248));
        btnHeader2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnHeader2.setText("FACTURAS");
        btnHeader2.setBorder(null);
        btnHeader2.setBorderPainted(false);
        btnHeader2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader.add(btnHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 0, 196, 70));

        btnHeader3.setBackground(new java.awt.Color(248, 248, 248));
        btnHeader3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnHeader3.setText("SERVICIOS");
        btnHeader3.setBorder(null);
        btnHeader3.setBorderPainted(false);
        btnHeader3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader.add(btnHeader3, new org.netbeans.lib.awtextra.AbsoluteConstraints(402, 0, 196, 70));

        btnHeader4.setBackground(new java.awt.Color(248, 248, 248));
        btnHeader4.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnHeader4.setText("GASTOS OPERATIVOS");
        btnHeader4.setBorder(null);
        btnHeader4.setBorderPainted(false);
        btnHeader4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader.add(btnHeader4, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 0, 240, 70));

        add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        pnlMain.setPreferredSize(new java.awt.Dimension(684, 694));
        pnlMain.setLayout(new java.awt.CardLayout());

        pnlMain1.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain1.setMinimumSize(new java.awt.Dimension(684, 685));
        pnlMain1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        subMain1.setBackground(new java.awt.Color(255, 255, 255));
        subMain1.setMinimumSize(new java.awt.Dimension(684, 685));
        subMain1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkEstado4.setText("NO DISPONIBLE");
        subMain1.add(checkEstado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnModificarSede3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnModificarSede3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTableEdit.png"))); // NOI18N
        btnModificarSede3.setText("MODIFICAR");
        btnModificarSede3.setToolTipText("");
        btnModificarSede3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarSede3.setIconTextGap(10);
        btnModificarSede3.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnModificarSede3.setMaximumSize(new java.awt.Dimension(125, 35));
        btnModificarSede3.setMinimumSize(new java.awt.Dimension(125, 35));
        btnModificarSede3.setPreferredSize(new java.awt.Dimension(125, 35));
        subMain1.add(btnModificarSede3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 160, 40));

        btnDeleteFromTable1.setBackground(new java.awt.Color(102, 0, 0));
        btnDeleteFromTable1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDeleteFromTable1.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFromTable1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ligth/iconTrash.png"))); // NOI18N
        btnDeleteFromTable1.setText("ELIMINAR");
        btnDeleteFromTable1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDeleteFromTable1.setIconTextGap(10);
        btnDeleteFromTable1.setMargin(new java.awt.Insets(2, 1, 3, 14));
        subMain1.add(btnDeleteFromTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 530, 160, 40));

        btnLoadForm.setBackground(new java.awt.Color(153, 255, 153));
        btnLoadForm.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnLoadForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnLoadForm.setText("<html>NUEVA<br>GUIA</html>");
        btnLoadForm.setToolTipText("");
        btnLoadForm.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnLoadForm.setIconTextGap(10);
        btnLoadForm.setMargin(new java.awt.Insets(2, 1, 3, 14));
        subMain1.add(btnLoadForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 160, 60));

        txtFilterSede3.setBackground(new java.awt.Color(242, 242, 242));
        txtFilterSede3.setBorder(null);
        txtFilterSede3.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtFilterSede3.setOpaque(true);
        subMain1.add(txtFilterSede3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 40));

        btnSearch4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearch4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearch4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch4.setOpaque(true);
        subMain1.add(btnSearch4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 40, 40));

        tblSedes2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tblSedes2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSedes2.setRowHeight(35);
        jScrollPane4.setViewportView(tblSedes2);

        subMain1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 980, 410));

        pnlMain1.add(subMain1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, -1, 650));

        subHeader1.setBackground(new java.awt.Color(255, 255, 255));
        subHeader1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHeader6.setBackground(new java.awt.Color(239, 255, 255));
        btnHeader6.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        btnHeader6.setText("<html>GESTIONAR<br>UBICACION</html>");
        btnHeader6.setBorder(null);
        btnHeader6.setBorderPainted(false);
        btnHeader6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHeader6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHeader6ActionPerformed(evt);
            }
        });
        subHeader1.add(btnHeader6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 196, 55));

        btnHeader7.setBackground(new java.awt.Color(239, 255, 255));
        btnHeader7.setFont(new java.awt.Font("Roboto", 3, 14)); // NOI18N
        btnHeader7.setText("<html>GESTIONAR<br>VIATICOS</html>");
        btnHeader7.setBorder(null);
        btnHeader7.setBorderPainted(false);
        btnHeader7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        subHeader1.add(btnHeader7, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 0, 196, 55));

        pnlMain1.add(subHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 15, 1000, 50));

        pnlMain.add(pnlMain1, "card2");

        pnlMain2.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain2.setMinimumSize(new java.awt.Dimension(684, 685));
        pnlMain2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkEstado8.setText("NO DISPONIBLE");
        pnlMain2.add(checkEstado8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnModificarSede7.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnModificarSede7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTableEdit.png"))); // NOI18N
        btnModificarSede7.setText("MODIFICAR");
        btnModificarSede7.setToolTipText("");
        btnModificarSede7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarSede7.setIconTextGap(10);
        btnModificarSede7.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnModificarSede7.setMaximumSize(new java.awt.Dimension(125, 35));
        btnModificarSede7.setMinimumSize(new java.awt.Dimension(125, 35));
        btnModificarSede7.setPreferredSize(new java.awt.Dimension(125, 35));
        pnlMain2.add(btnModificarSede7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 160, 40));

        btnDeleteFromTable5.setBackground(new java.awt.Color(102, 0, 0));
        btnDeleteFromTable5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDeleteFromTable5.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFromTable5.setText("ELIMINAR");
        btnDeleteFromTable5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDeleteFromTable5.setIconTextGap(10);
        btnDeleteFromTable5.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain2.add(btnDeleteFromTable5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 610, 160, 40));

        btnFormModifyTransportista5.setBackground(new java.awt.Color(153, 255, 153));
        btnFormModifyTransportista5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnFormModifyTransportista5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnFormModifyTransportista5.setText("<html>REGISTAR<br>TRANSPORTISTA</html>");
        btnFormModifyTransportista5.setToolTipText("");
        btnFormModifyTransportista5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFormModifyTransportista5.setIconTextGap(10);
        btnFormModifyTransportista5.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain2.add(btnFormModifyTransportista5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 160, 60));

        txtFilterSede7.setBackground(new java.awt.Color(242, 242, 242));
        txtFilterSede7.setBorder(null);
        txtFilterSede7.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtFilterSede7.setOpaque(true);
        pnlMain2.add(txtFilterSede7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 40));

        btnSearch8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearch8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearch8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch8.setOpaque(true);
        pnlMain2.add(btnSearch8, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 40, 40));

        tblSedes6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tblSedes6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSedes6.setRowHeight(35);
        jScrollPane8.setViewportView(tblSedes6);

        pnlMain2.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 980, 490));

        pnlMain.add(pnlMain2, "card2");

        pnlMain3.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain3.setMinimumSize(new java.awt.Dimension(684, 685));
        pnlMain3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkEstado5.setText("NO DISPONIBLE");
        pnlMain3.add(checkEstado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnModificarSede4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnModificarSede4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTableEdit.png"))); // NOI18N
        btnModificarSede4.setText("MODIFICAR");
        btnModificarSede4.setToolTipText("");
        btnModificarSede4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarSede4.setIconTextGap(10);
        btnModificarSede4.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnModificarSede4.setMaximumSize(new java.awt.Dimension(125, 35));
        btnModificarSede4.setMinimumSize(new java.awt.Dimension(125, 35));
        btnModificarSede4.setPreferredSize(new java.awt.Dimension(125, 35));
        pnlMain3.add(btnModificarSede4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 160, 40));

        btnDeleteFromTable2.setBackground(new java.awt.Color(102, 0, 0));
        btnDeleteFromTable2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDeleteFromTable2.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFromTable2.setText("ELIMINAR");
        btnDeleteFromTable2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDeleteFromTable2.setIconTextGap(10);
        btnDeleteFromTable2.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain3.add(btnDeleteFromTable2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 610, 160, 40));

        btnFormModifyTransportista2.setBackground(new java.awt.Color(153, 255, 153));
        btnFormModifyTransportista2.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnFormModifyTransportista2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnFormModifyTransportista2.setText("<html>REGISTAR<br>TRANSPORTISTA</html>");
        btnFormModifyTransportista2.setToolTipText("");
        btnFormModifyTransportista2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFormModifyTransportista2.setIconTextGap(10);
        btnFormModifyTransportista2.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain3.add(btnFormModifyTransportista2, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 160, 60));

        txtFilterSede4.setBackground(new java.awt.Color(242, 242, 242));
        txtFilterSede4.setBorder(null);
        txtFilterSede4.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtFilterSede4.setOpaque(true);
        pnlMain3.add(txtFilterSede4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 40));

        btnSearch5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearch5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearch5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch5.setOpaque(true);
        pnlMain3.add(btnSearch5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 40, 40));

        tblSedes3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tblSedes3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSedes3.setRowHeight(35);
        jScrollPane5.setViewportView(tblSedes3);

        pnlMain3.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 980, 490));

        pnlMain.add(pnlMain3, "card2");

        pnlMain4.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain4.setMinimumSize(new java.awt.Dimension(684, 685));
        pnlMain4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkEstado6.setText("NO DISPONIBLE");
        pnlMain4.add(checkEstado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnModificarSede5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnModificarSede5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTableEdit.png"))); // NOI18N
        btnModificarSede5.setText("MODIFICAR");
        btnModificarSede5.setToolTipText("");
        btnModificarSede5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarSede5.setIconTextGap(10);
        btnModificarSede5.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnModificarSede5.setMaximumSize(new java.awt.Dimension(125, 35));
        btnModificarSede5.setMinimumSize(new java.awt.Dimension(125, 35));
        btnModificarSede5.setPreferredSize(new java.awt.Dimension(125, 35));
        pnlMain4.add(btnModificarSede5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 160, 40));

        btnDeleteFromTable3.setBackground(new java.awt.Color(102, 0, 0));
        btnDeleteFromTable3.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDeleteFromTable3.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFromTable3.setText("ELIMINAR");
        btnDeleteFromTable3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDeleteFromTable3.setIconTextGap(10);
        btnDeleteFromTable3.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain4.add(btnDeleteFromTable3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 610, 160, 40));

        btnFormModifyTransportista3.setBackground(new java.awt.Color(153, 255, 153));
        btnFormModifyTransportista3.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnFormModifyTransportista3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnFormModifyTransportista3.setText("<html>REGISTAR<br>TRANSPORTISTA</html>");
        btnFormModifyTransportista3.setToolTipText("");
        btnFormModifyTransportista3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFormModifyTransportista3.setIconTextGap(10);
        btnFormModifyTransportista3.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain4.add(btnFormModifyTransportista3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 160, 60));

        txtFilterSede5.setBackground(new java.awt.Color(242, 242, 242));
        txtFilterSede5.setBorder(null);
        txtFilterSede5.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtFilterSede5.setOpaque(true);
        pnlMain4.add(txtFilterSede5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 40));

        btnSearch6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearch6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearch6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch6.setOpaque(true);
        pnlMain4.add(btnSearch6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 40, 40));

        tblSedes4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tblSedes4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSedes4.setRowHeight(35);
        jScrollPane6.setViewportView(tblSedes4);

        pnlMain4.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 980, 490));

        pnlMain.add(pnlMain4, "card2");

        pnlMain5.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain5.setMinimumSize(new java.awt.Dimension(684, 685));
        pnlMain5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkEstado7.setText("NO DISPONIBLE");
        pnlMain5.add(checkEstado7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnModificarSede6.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnModificarSede6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTableEdit.png"))); // NOI18N
        btnModificarSede6.setText("MODIFICAR");
        btnModificarSede6.setToolTipText("");
        btnModificarSede6.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarSede6.setIconTextGap(10);
        btnModificarSede6.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnModificarSede6.setMaximumSize(new java.awt.Dimension(125, 35));
        btnModificarSede6.setMinimumSize(new java.awt.Dimension(125, 35));
        btnModificarSede6.setPreferredSize(new java.awt.Dimension(125, 35));
        pnlMain5.add(btnModificarSede6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 160, 40));

        btnDeleteFromTable4.setBackground(new java.awt.Color(102, 0, 0));
        btnDeleteFromTable4.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDeleteFromTable4.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFromTable4.setText("ELIMINAR");
        btnDeleteFromTable4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDeleteFromTable4.setIconTextGap(10);
        btnDeleteFromTable4.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain5.add(btnDeleteFromTable4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 610, 160, 40));

        btnFormModifyTransportista4.setBackground(new java.awt.Color(153, 255, 153));
        btnFormModifyTransportista4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnFormModifyTransportista4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnFormModifyTransportista4.setText("<html>REGISTAR<br>TRANSPORTISTA</html>");
        btnFormModifyTransportista4.setToolTipText("");
        btnFormModifyTransportista4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFormModifyTransportista4.setIconTextGap(10);
        btnFormModifyTransportista4.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain5.add(btnFormModifyTransportista4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 160, 60));

        txtFilterSede6.setBackground(new java.awt.Color(242, 242, 242));
        txtFilterSede6.setBorder(null);
        txtFilterSede6.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtFilterSede6.setOpaque(true);
        pnlMain5.add(txtFilterSede6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 40));

        btnSearch7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearch7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearch7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch7.setOpaque(true);
        pnlMain5.add(btnSearch7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 40, 40));

        tblSedes5.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tblSedes5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSedes5.setRowHeight(35);
        jScrollPane7.setViewportView(tblSedes5);

        pnlMain5.add(jScrollPane7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 980, 490));

        pnlMain.add(pnlMain5, "card2");

        add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1000, 660));
    }// </editor-fold>//GEN-END:initComponents

    private void btnHeader6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHeader6ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnHeader6ActionPerformed
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDeleteFromTable1;
    public javax.swing.JButton btnDeleteFromTable2;
    public javax.swing.JButton btnDeleteFromTable3;
    public javax.swing.JButton btnDeleteFromTable4;
    public javax.swing.JButton btnDeleteFromTable5;
    public javax.swing.JButton btnFormModifyTransportista2;
    public javax.swing.JButton btnFormModifyTransportista3;
    public javax.swing.JButton btnFormModifyTransportista4;
    public javax.swing.JButton btnFormModifyTransportista5;
    public javax.swing.JToggleButton btnHeader1;
    public javax.swing.JToggleButton btnHeader2;
    public javax.swing.JToggleButton btnHeader3;
    public javax.swing.JToggleButton btnHeader4;
    public javax.swing.JToggleButton btnHeader6;
    public javax.swing.JToggleButton btnHeader7;
    public javax.swing.JButton btnLoadForm;
    public javax.swing.JButton btnModificarSede3;
    public javax.swing.JButton btnModificarSede4;
    public javax.swing.JButton btnModificarSede5;
    public javax.swing.JButton btnModificarSede6;
    public javax.swing.JButton btnModificarSede7;
    private javax.swing.JLabel btnSearch4;
    private javax.swing.JLabel btnSearch5;
    private javax.swing.JLabel btnSearch6;
    private javax.swing.JLabel btnSearch7;
    private javax.swing.JLabel btnSearch8;
    public javax.swing.JCheckBox checkEstado4;
    public javax.swing.JCheckBox checkEstado5;
    public javax.swing.JCheckBox checkEstado6;
    public javax.swing.JCheckBox checkEstado7;
    public javax.swing.JCheckBox checkEstado8;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    public javax.swing.JPanel pnlMain1;
    public javax.swing.JPanel pnlMain2;
    public javax.swing.JPanel pnlMain3;
    public javax.swing.JPanel pnlMain4;
    public javax.swing.JPanel pnlMain5;
    private javax.swing.JPanel subHeader1;
    public javax.swing.JPanel subMain1;
    public javax.swing.JTable tblSedes2;
    public javax.swing.JTable tblSedes3;
    public javax.swing.JTable tblSedes4;
    public javax.swing.JTable tblSedes5;
    public javax.swing.JTable tblSedes6;
    public javax.swing.JTextField txtFilterSede3;
    public javax.swing.JTextField txtFilterSede4;
    public javax.swing.JTextField txtFilterSede5;
    public javax.swing.JTextField txtFilterSede6;
    public javax.swing.JTextField txtFilterSede7;
    // End of variables declaration//GEN-END:variables
}
