/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TRANSPORTE.VISTAS.REPORTES;

/**
 *
 * @author milag
 */
public class mainReporte extends javax.swing.JPanel {

    /**
     * Creates new form mainReporte
     */
    public mainReporte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormPersona = new javax.swing.JPanel();
        pnlUser1 = new javax.swing.JPanel();
        lblTitlePersona = new javax.swing.JLabel();
        lblInfoReporte = new javax.swing.JLabel();
        btnClienteMasSolicitados = new javax.swing.JToggleButton();
        btnTranportistaMasViajes = new javax.swing.JToggleButton();
        btnViajesMasRealizados = new javax.swing.JToggleButton();
        btnCancelFormReporte = new javax.swing.JButton();
        btnCleanFormViatico = new javax.swing.JButton();
        btnSetFormViatico = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblFormReporte = new javax.swing.JTable();

        pnlFormPersona.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormPersona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUser1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitlePersona.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitlePersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePersona.setText("GENERAR REPORTE");

        lblInfoReporte.setForeground(new java.awt.Color(255, 0, 51));
        lblInfoReporte.setText("* ");

        btnClienteMasSolicitados.setBackground(new java.awt.Color(204, 255, 255));
        btnClienteMasSolicitados.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnClienteMasSolicitados.setText("<html>Cliente con mas<br>viajes solicitados</html>");
        btnClienteMasSolicitados.setBorder(null);
        btnClienteMasSolicitados.setBorderPainted(false);
        btnClienteMasSolicitados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClienteMasSolicitados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClienteMasSolicitadosActionPerformed(evt);
            }
        });

        btnTranportistaMasViajes.setBackground(new java.awt.Color(204, 255, 255));
        btnTranportistaMasViajes.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnTranportistaMasViajes.setText("<html>Transportista con mas<br>viajes realizados</html>");
        btnTranportistaMasViajes.setBorder(null);
        btnTranportistaMasViajes.setBorderPainted(false);
        btnTranportistaMasViajes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTranportistaMasViajes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTranportistaMasViajesActionPerformed(evt);
            }
        });

        btnViajesMasRealizados.setBackground(new java.awt.Color(204, 255, 255));
        btnViajesMasRealizados.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnViajesMasRealizados.setText("<html>Viajes mas<br>solicitados</html>");
        btnViajesMasRealizados.setBorder(null);
        btnViajesMasRealizados.setBorderPainted(false);
        btnViajesMasRealizados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViajesMasRealizados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViajesMasRealizadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlUser1Layout = new javax.swing.GroupLayout(pnlUser1);
        pnlUser1.setLayout(pnlUser1Layout);
        pnlUser1Layout.setHorizontalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUser1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(pnlUser1Layout.createSequentialGroup()
                            .addComponent(btnTranportistaMasViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(47, 47, 47)
                            .addComponent(btnClienteMasSolicitados, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnViajesMasRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(lblTitlePersona, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblInfoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        pnlUser1Layout.setVerticalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblTitlePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblInfoReporte, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTranportistaMasViajes, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClienteMasSolicitados, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViajesMasRealizados, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pnlFormPersona.add(pnlUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 230));

        btnCancelFormReporte.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelFormReporte.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelFormReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelFormReporte.setText("CANCELAR");
        btnCancelFormReporte.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelFormReporte.setIconTextGap(10);
        btnCancelFormReporte.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlFormPersona.add(btnCancelFormReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 620, 160, 40));

        btnCleanFormViatico.setBackground(new java.awt.Color(230, 230, 230));
        btnCleanFormViatico.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCleanFormViatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMop.png"))); // NOI18N
        btnCleanFormViatico.setText("LIMPIAR");
        btnCleanFormViatico.setToolTipText("");
        btnCleanFormViatico.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCleanFormViatico.setIconTextGap(10);
        btnCleanFormViatico.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCleanFormViatico.setMaximumSize(new java.awt.Dimension(125, 35));
        btnCleanFormViatico.setMinimumSize(new java.awt.Dimension(125, 35));
        btnCleanFormViatico.setPreferredSize(new java.awt.Dimension(125, 35));
        pnlFormPersona.add(btnCleanFormViatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 620, 160, 40));

        btnSetFormViatico.setBackground(new java.awt.Color(153, 255, 153));
        btnSetFormViatico.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSetFormViatico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnSetFormViatico.setText("IMPRIMIR");
        btnSetFormViatico.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSetFormViatico.setIconTextGap(10);
        btnSetFormViatico.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pnlFormPersona.add(btnSetFormViatico, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 620, 170, 40));

        tblFormReporte.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        tblFormReporte.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFormReporte.setRowHeight(40);
        tblFormReporte.setRowMargin(10);
        jScrollPane4.setViewportView(tblFormReporte);

        pnlFormPersona.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 750, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFormPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 798, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlFormPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 683, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnClienteMasSolicitadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClienteMasSolicitadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnClienteMasSolicitadosActionPerformed

    private void btnTranportistaMasViajesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTranportistaMasViajesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTranportistaMasViajesActionPerformed

    private void btnViajesMasRealizadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViajesMasRealizadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViajesMasRealizadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelFormReporte;
    public javax.swing.JButton btnCleanFormViatico;
    public javax.swing.JToggleButton btnClienteMasSolicitados;
    public javax.swing.JButton btnSetFormViatico;
    public javax.swing.JToggleButton btnTranportistaMasViajes;
    public javax.swing.JToggleButton btnViajesMasRealizados;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JLabel lblInfoReporte;
    public javax.swing.JLabel lblTitlePersona;
    private javax.swing.JPanel pnlFormPersona;
    public javax.swing.JPanel pnlUser1;
    public javax.swing.JTable tblFormReporte;
    // End of variables declaration//GEN-END:variables
}
