/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TRANSPORTE.VISTAS.TRANSPORTISTAS;

/**
 *
 * @author arnal
 */
public class formTransportista extends javax.swing.JFrame {

    /**
     * Creates new form formPersonas
     */
    public formTransportista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFormPersona = new javax.swing.JPanel();
        pnlUser1 = new javax.swing.JPanel();
        lblTitlePersona = new javax.swing.JLabel();
        lblEstatusPersona = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtNombrePersona = new javax.swing.JTextField();
        lblCedula3 = new javax.swing.JLabel();
        txtDocumentoPersona = new javax.swing.JTextField();
        txtTelefonoPersona = new javax.swing.JTextField();
        lblCategoria1 = new javax.swing.JLabel();
        lblInfoPersona = new javax.swing.JLabel();
        lblControlFormPersona = new javax.swing.JLabel();
        lblCategoria6 = new javax.swing.JLabel();
        txtCorreoPersona = new javax.swing.JTextField();
        lblCategoria7 = new javax.swing.JLabel();
        lblCategoria8 = new javax.swing.JLabel();
        jcbxCaegoriaPersona = new javax.swing.JComboBox<>();
        jcbxTipoPersona = new javax.swing.JComboBox<>();
        lblCategoria3 = new javax.swing.JLabel();
        jcbxEstadoPersona = new javax.swing.JComboBox<>();
        btnCancelFormPersona = new javax.swing.JButton();
        btnCleanFormPersona = new javax.swing.JButton();
        btnSetFormPersona = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblFormPersonas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFormPersona.setBackground(new java.awt.Color(255, 255, 255));
        pnlFormPersona.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUser1.setBackground(new java.awt.Color(255, 255, 255));

        lblTitlePersona.setFont(new java.awt.Font("Roboto Black", 3, 24)); // NOI18N
        lblTitlePersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitlePersona.setText("REGISTRAR TRANSPORTISTA");

        lblEstatusPersona.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblEstatusPersona.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEstatusPersona.setText("0");
        lblEstatusPersona.setEnabled(false);

        lblNombre1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblNombre1.setText("NOMBRE");

        txtNombrePersona.setBackground(new java.awt.Color(250, 250, 250));
        txtNombrePersona.setForeground(new java.awt.Color(0, 0, 0));
        txtNombrePersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtNombrePersona.setCaretColor(new java.awt.Color(0, 0, 0));
        txtNombrePersona.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombrePersona.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtNombrePersona.setOpaque(true);

        lblCedula3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCedula3.setText("DOCUMENTO");

        txtDocumentoPersona.setBackground(new java.awt.Color(250, 250, 250));
        txtDocumentoPersona.setForeground(new java.awt.Color(0, 0, 0));
        txtDocumentoPersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtDocumentoPersona.setCaretColor(new java.awt.Color(0, 0, 0));
        txtDocumentoPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtDocumentoPersona.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDocumentoPersona.setOpaque(true);

        txtTelefonoPersona.setBackground(new java.awt.Color(250, 250, 250));
        txtTelefonoPersona.setForeground(new java.awt.Color(0, 0, 0));
        txtTelefonoPersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtTelefonoPersona.setCaretColor(new java.awt.Color(0, 0, 0));
        txtTelefonoPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTelefonoPersona.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtTelefonoPersona.setOpaque(true);

        lblCategoria1.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria1.setText("TELEFONO");

        lblInfoPersona.setForeground(new java.awt.Color(255, 0, 51));
        lblInfoPersona.setText("* ");

        lblControlFormPersona.setText("1");

        lblCategoria6.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria6.setText("CORREO");

        txtCorreoPersona.setBackground(new java.awt.Color(250, 250, 250));
        txtCorreoPersona.setForeground(new java.awt.Color(0, 0, 0));
        txtCorreoPersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        txtCorreoPersona.setCaretColor(new java.awt.Color(0, 0, 0));
        txtCorreoPersona.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtCorreoPersona.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtCorreoPersona.setOpaque(true);

        lblCategoria7.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria7.setText("TIPO");

        lblCategoria8.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria8.setText("CATEGORIA");

        jcbxCaegoriaPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CLIENTE", "TRANSPORTISTA", "PROPIETARIO" }));
        jcbxCaegoriaPersona.setSelectedIndex(1);
        jcbxCaegoriaPersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jcbxCaegoriaPersona.setEnabled(false);

        jcbxTipoPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "V", "E", "J", "G" }));
        jcbxTipoPersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblCategoria3.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        lblCategoria3.setText("ESTADO");

        jcbxEstadoPersona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NO DISPONIBLE", "DISPONIBLE" }));
        jcbxEstadoPersona.setSelectedIndex(1);
        jcbxEstadoPersona.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jcbxEstadoPersona.setEnabled(false);

        javax.swing.GroupLayout pnlUser1Layout = new javax.swing.GroupLayout(pnlUser1);
        pnlUser1.setLayout(pnlUser1Layout);
        pnlUser1Layout.setHorizontalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlUser1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTitlePersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                .addComponent(lblEstatusPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblInfoPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                .addComponent(lblCedula3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDocumentoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlUser1Layout.createSequentialGroup()
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCategoria1)
                                    .addComponent(lblCategoria7))
                                .addGap(30, 30, 30)
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jcbxEstadoPersona, 0, 184, Short.MAX_VALUE)
                                    .addComponent(txtTelefonoPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(jcbxTipoPersona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCategoria8)
                                    .addComponent(lblCategoria6))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombrePersona, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(txtCorreoPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(jcbxCaegoriaPersona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(33, 33, 33))
            .addGroup(pnlUser1Layout.createSequentialGroup()
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(lblControlFormPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCategoria3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlUser1Layout.setVerticalGroup(
            pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                .addComponent(lblControlFormPersona)
                .addGap(9, 9, 9)
                .addComponent(lblTitlePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser1Layout.createSequentialGroup()
                        .addComponent(lblEstatusPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlUser1Layout.createSequentialGroup()
                        .addComponent(lblInfoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula3)
                    .addComponent(txtDocumentoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre1)
                    .addComponent(txtNombrePersona, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCorreoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCategoria6))
                    .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTelefonoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCategoria1)))
                .addGap(18, 18, 18)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCategoria8)
                        .addComponent(jcbxCaegoriaPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblCategoria7)
                    .addComponent(jcbxTipoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCategoria3)
                    .addComponent(jcbxEstadoPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pnlFormPersona.add(pnlUser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 780, 300));

        btnCancelFormPersona.setBackground(new java.awt.Color(102, 0, 0));
        btnCancelFormPersona.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCancelFormPersona.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelFormPersona.setText("CANCELAR");
        btnCancelFormPersona.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCancelFormPersona.setIconTextGap(10);
        btnCancelFormPersona.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlFormPersona.add(btnCancelFormPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 570, 160, 40));

        btnCleanFormPersona.setBackground(new java.awt.Color(230, 230, 230));
        btnCleanFormPersona.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnCleanFormPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconMop.png"))); // NOI18N
        btnCleanFormPersona.setText("LIMPIAR");
        btnCleanFormPersona.setToolTipText("");
        btnCleanFormPersona.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnCleanFormPersona.setIconTextGap(10);
        btnCleanFormPersona.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnCleanFormPersona.setMaximumSize(new java.awt.Dimension(125, 35));
        btnCleanFormPersona.setMinimumSize(new java.awt.Dimension(125, 35));
        btnCleanFormPersona.setPreferredSize(new java.awt.Dimension(125, 35));
        pnlFormPersona.add(btnCleanFormPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 570, 160, 40));

        btnSetFormPersona.setBackground(new java.awt.Color(153, 255, 153));
        btnSetFormPersona.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnSetFormPersona.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnSetFormPersona.setText("REGISTRAR");
        btnSetFormPersona.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnSetFormPersona.setIconTextGap(10);
        btnSetFormPersona.setMargin(new java.awt.Insets(0, 0, 0, 0));
        pnlFormPersona.add(btnSetFormPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 570, 190, 40));

        tblFormPersonas.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        tblFormPersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblFormPersonas.setRowHeight(40);
        tblFormPersonas.setRowMargin(10);
        jScrollPane4.setViewportView(tblFormPersonas);

        pnlFormPersona.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 750, 250));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFormPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelFormPersona;
    public javax.swing.JButton btnCleanFormPersona;
    public javax.swing.JButton btnSetFormPersona;
    private javax.swing.JScrollPane jScrollPane4;
    public javax.swing.JComboBox<String> jcbxCaegoriaPersona;
    public javax.swing.JComboBox<String> jcbxEstadoPersona;
    public javax.swing.JComboBox<String> jcbxTipoPersona;
    public javax.swing.JLabel lblCategoria1;
    public javax.swing.JLabel lblCategoria3;
    public javax.swing.JLabel lblCategoria6;
    public javax.swing.JLabel lblCategoria7;
    public javax.swing.JLabel lblCategoria8;
    public javax.swing.JLabel lblCedula3;
    public javax.swing.JLabel lblControlFormPersona;
    public javax.swing.JLabel lblEstatusPersona;
    public javax.swing.JLabel lblInfoPersona;
    public javax.swing.JLabel lblNombre1;
    public javax.swing.JLabel lblTitlePersona;
    private javax.swing.JPanel pnlFormPersona;
    public javax.swing.JPanel pnlUser1;
    public javax.swing.JTable tblFormPersonas;
    public javax.swing.JTextField txtCorreoPersona;
    public javax.swing.JTextField txtDocumentoPersona;
    public javax.swing.JTextField txtNombrePersona;
    public javax.swing.JTextField txtTelefonoPersona;
    // End of variables declaration//GEN-END:variables
}
