/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package TRANSPORTE.VISTAS.TRANSPORTISTAS;

/**
 *
 * @author arnal
 */
public class mainTransportistas extends javax.swing.JPanel {

    /**
     * Creates new form Dashboard
     */

    public mainTransportistas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlHeader = new javax.swing.JPanel();
        btnHeader1 = new javax.swing.JToggleButton();
        btnHeader2 = new javax.swing.JToggleButton();
        pnlMain = new javax.swing.JPanel();
        pnlMain1 = new javax.swing.JPanel();
        checkEstado2 = new javax.swing.JCheckBox();
        btnModificarSede1 = new javax.swing.JButton();
        btnDeleteFromTable = new javax.swing.JButton();
        btnFormModifyTransportista = new javax.swing.JButton();
        txtFilterSede1 = new javax.swing.JTextField();
        btnSearch2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSedes1 = new javax.swing.JTable();
        pnlMain2 = new javax.swing.JPanel();
        checkEstado3 = new javax.swing.JCheckBox();
        btnModificarSede2 = new javax.swing.JButton();
        btnDeleteFromTable1 = new javax.swing.JButton();
        btnFormModifyTransportista1 = new javax.swing.JButton();
        txtFilterSede2 = new javax.swing.JTextField();
        btnSearch3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSedes2 = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(684, 694));
        setName("prestamos"); // NOI18N
        setPreferredSize(new java.awt.Dimension(684, 694));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlHeader.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHeader1.setBackground(new java.awt.Color(248, 248, 248));
        btnHeader1.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnHeader1.setSelected(true);
        btnHeader1.setText("TRANSPORTISTAS");
        btnHeader1.setBorder(null);
        btnHeader1.setBorderPainted(false);
        btnHeader1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader.add(btnHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 212, 70));

        btnHeader2.setBackground(new java.awt.Color(248, 248, 248));
        btnHeader2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btnHeader2.setText("LICENCIAS");
        btnHeader2.setBorder(null);
        btnHeader2.setBorderPainted(false);
        btnHeader2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlHeader.add(btnHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 212, 70));

        add(pnlHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 70));

        pnlMain.setPreferredSize(new java.awt.Dimension(684, 694));
        pnlMain.setLayout(new java.awt.CardLayout());

        pnlMain1.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain1.setMinimumSize(new java.awt.Dimension(684, 685));
        pnlMain1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkEstado2.setText("NO DISPONIBLE");
        pnlMain1.add(checkEstado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnModificarSede1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnModificarSede1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTableEdit.png"))); // NOI18N
        btnModificarSede1.setText("MODIFICAR");
        btnModificarSede1.setToolTipText("");
        btnModificarSede1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarSede1.setIconTextGap(10);
        btnModificarSede1.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnModificarSede1.setMaximumSize(new java.awt.Dimension(125, 35));
        btnModificarSede1.setMinimumSize(new java.awt.Dimension(125, 35));
        btnModificarSede1.setPreferredSize(new java.awt.Dimension(125, 35));
        pnlMain1.add(btnModificarSede1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 160, 40));

        btnDeleteFromTable.setBackground(new java.awt.Color(102, 0, 0));
        btnDeleteFromTable.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDeleteFromTable.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFromTable.setText("ELIMINAR");
        btnDeleteFromTable.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDeleteFromTable.setIconTextGap(10);
        btnDeleteFromTable.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain1.add(btnDeleteFromTable, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 610, 160, 40));

        btnFormModifyTransportista.setBackground(new java.awt.Color(153, 255, 153));
        btnFormModifyTransportista.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnFormModifyTransportista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnFormModifyTransportista.setText("<html>REGISTAR<br>TRANSPORTISTA</html>");
        btnFormModifyTransportista.setToolTipText("");
        btnFormModifyTransportista.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFormModifyTransportista.setIconTextGap(10);
        btnFormModifyTransportista.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain1.add(btnFormModifyTransportista, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 160, 60));

        txtFilterSede1.setBackground(new java.awt.Color(242, 242, 242));
        txtFilterSede1.setBorder(null);
        txtFilterSede1.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtFilterSede1.setOpaque(true);
        pnlMain1.add(txtFilterSede1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 40));

        btnSearch2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearch2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearch2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch2.setOpaque(true);
        pnlMain1.add(btnSearch2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 40, 40));

        tblSedes1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tblSedes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSedes1.setRowHeight(35);
        jScrollPane3.setViewportView(tblSedes1);

        pnlMain1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 980, 490));

        pnlMain.add(pnlMain1, "card2");

        pnlMain2.setBackground(new java.awt.Color(255, 255, 255));
        pnlMain2.setMinimumSize(new java.awt.Dimension(684, 685));
        pnlMain2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        checkEstado3.setText("NO DISPONIBLE");
        pnlMain2.add(checkEstado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        btnModificarSede2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnModificarSede2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconTableEdit.png"))); // NOI18N
        btnModificarSede2.setText("MODIFICAR");
        btnModificarSede2.setToolTipText("");
        btnModificarSede2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnModificarSede2.setIconTextGap(10);
        btnModificarSede2.setMargin(new java.awt.Insets(2, 1, 3, 14));
        btnModificarSede2.setMaximumSize(new java.awt.Dimension(125, 35));
        btnModificarSede2.setMinimumSize(new java.awt.Dimension(125, 35));
        btnModificarSede2.setPreferredSize(new java.awt.Dimension(125, 35));
        pnlMain2.add(btnModificarSede2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 160, 40));

        btnDeleteFromTable1.setBackground(new java.awt.Color(102, 0, 0));
        btnDeleteFromTable1.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        btnDeleteFromTable1.setForeground(new java.awt.Color(255, 255, 255));
        btnDeleteFromTable1.setText("ELIMINAR");
        btnDeleteFromTable1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDeleteFromTable1.setIconTextGap(10);
        btnDeleteFromTable1.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain2.add(btnDeleteFromTable1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 610, 160, 40));

        btnFormModifyTransportista1.setBackground(new java.awt.Color(153, 255, 153));
        btnFormModifyTransportista1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        btnFormModifyTransportista1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconAdd.png"))); // NOI18N
        btnFormModifyTransportista1.setText("<html>REGISTAR<br>LICENCIA</html>");
        btnFormModifyTransportista1.setToolTipText("");
        btnFormModifyTransportista1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnFormModifyTransportista1.setIconTextGap(10);
        btnFormModifyTransportista1.setMargin(new java.awt.Insets(2, 1, 3, 14));
        pnlMain2.add(btnFormModifyTransportista1, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 20, 160, 60));

        txtFilterSede2.setBackground(new java.awt.Color(242, 242, 242));
        txtFilterSede2.setBorder(null);
        txtFilterSede2.setMargin(new java.awt.Insets(0, 10, 0, 0));
        txtFilterSede2.setOpaque(true);
        pnlMain2.add(txtFilterSede2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 280, 40));

        btnSearch3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        btnSearch3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconSearch.png"))); // NOI18N
        btnSearch3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSearch3.setOpaque(true);
        pnlMain2.add(btnSearch3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 40, 40));

        tblSedes2.setFont(new java.awt.Font("Roboto", 1, 12)); // NOI18N
        tblSedes2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSedes2.setRowHeight(35);
        jScrollPane4.setViewportView(tblSedes2);

        pnlMain2.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 980, 490));

        pnlMain.add(pnlMain2, "card2");

        add(pnlMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1000, 660));
    }// </editor-fold>//GEN-END:initComponents
    
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDeleteFromTable;
    public javax.swing.JButton btnDeleteFromTable1;
    public javax.swing.JButton btnFormModifyTransportista;
    public javax.swing.JButton btnFormModifyTransportista1;
    public javax.swing.JToggleButton btnHeader1;
    public javax.swing.JToggleButton btnHeader2;
    public javax.swing.JButton btnModificarSede1;
    public javax.swing.JButton btnModificarSede2;
    private javax.swing.JLabel btnSearch2;
    private javax.swing.JLabel btnSearch3;
    public javax.swing.JCheckBox checkEstado2;
    public javax.swing.JCheckBox checkEstado3;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlMain;
    public javax.swing.JPanel pnlMain1;
    public javax.swing.JPanel pnlMain2;
    public javax.swing.JTable tblSedes1;
    public javax.swing.JTable tblSedes2;
    public javax.swing.JTextField txtFilterSede1;
    public javax.swing.JTextField txtFilterSede2;
    // End of variables declaration//GEN-END:variables
}
